import type { SemanticRegistryFormDefinition } from "./types";

export const SEMANTIC_TENDER_FIELD_REGISTRY: Record<string, SemanticRegistryFormDefinition> = {
  SBD1: {
    formId: "SBD1",
    fields: [
      {
        fieldId: "company_name",
        aliases: ["NAME OF BIDDER", "BIDDER NAME", "COMPANY NAME", "LEGAL ENTITY NAME"],
        sourcePath: "contractor.companyName",
        semanticKey: "companyName",
        fieldType: "text",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "postal_address",
        aliases: ["POSTAL ADDRESS", "MAILING ADDRESS", "POST ADDRESS"],
        sourcePath: "contractor.postalAddress",
        semanticKey: "postalAddress",
        fieldType: "text",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "street_address",
        aliases: ["STREET ADDRESS", "PHYSICAL ADDRESS", "BUSINESS ADDRESS"],
        sourcePath: "contractor.streetAddress",
        semanticKey: "streetAddress",
        fieldType: "text",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "telephone",
        aliases: ["TELEPHONE NUMBER", "TEL NUMBER", "PHONE NUMBER", "BUSINESS TELEPHONE"],
        sourcePath: "contractor.phone",
        semanticKey: "phone",
        fieldType: "text",
        required: false,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "email",
        aliases: ["E-MAIL ADDRESS", "EMAIL ADDRESS", "E MAIL ADDRESS"],
        sourcePath: "contractor.email",
        semanticKey: "email",
        fieldType: "text",
        required: false,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "vat_number",
        aliases: ["VAT REGISTRATION NUMBER", "VAT NUMBER"],
        sourcePath: "contractor.vatNumber",
        semanticKey: "vatNumber",
        fieldType: "text",
        required: false,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "tax_pin",
        aliases: ["TAX COMPLIANCE SYSTEM PIN", "TAX PIN", "TAX CLEARANCE PIN"],
        sourcePath: "contractor.taxPin",
        semanticKey: "taxPin",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "csd_number",
        aliases: ["CENTRAL SUPPLIER DATABASE NO", "CSD NUMBER", "CENTRAL SUPPLIER DATABASE NUMBER"],
        sourcePath: "contractor.csdNumber",
        semanticKey: "csdNumber",
        fieldType: "text",
        required: false,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "registration_number",
        aliases: ["REGISTRATION NUMBER", "COMPANY REG NUMBER", "CK NUMBER", "ENTITY REGISTRATION"],
        sourcePath: "contractor.regNumber",
        semanticKey: "regNumber",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "foreign_supplier_yes",
        aliases: ["ARE YOU A FOREIGN BASED SUPPLIER", "FOREIGN SUPPLIER", "OVERSEAS SUPPLIER"],
        sourcePath: "semantic.foreignSupplier",
        semanticKey: "foreignSupplierYes",
        fieldType: "checkbox",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "foreign_supplier_no",
        aliases: ["ARE YOU A FOREIGN BASED SUPPLIER", "FOREIGN SUPPLIER", "OVERSEAS SUPPLIER"],
        sourcePath: "semantic.foreignSupplier",
        semanticKey: "foreignSupplierNo",
        fieldType: "checkbox",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "bbbee_status",
        aliases: [
          "B-BBEE STATUS LEVEL VERIFICATION CERTIFICATE",
          "B-BBEE STATUS LEVEL",
          "BEE STATUS LEVEL",
        ],
        sourcePath: "contractor.bbbeeLevel",
        semanticKey: "bbbeeLevel",
        fieldType: "text",
        required: false,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "bbbee_issue_date",
        aliases: ["B-BBEE ISSUE DATE", "B-BBEE CERTIFICATE ISSUE DATE", "DATE OF ISSUE", "ISSUE DATE"],
        sourcePath: "contractor.bbbeeIssueDate",
        semanticKey: "bbbeeIssueDate",
        fieldType: "date",
        required: false,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "signature_name",
        aliases: ["SIGNATURE OF BIDDER", "SIGNATURE", "AUTHORISED SIGNATORY"],
        sourcePath: "semantic.signatureName",
        semanticKey: "signatureName",
        fieldType: "signature",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "date",
        aliases: ["DATE SIGNED", "SIGNATURE DATE", "FORM DATE", "DATE"],
        sourcePath: "semantic.today",
        semanticKey: "today",
        fieldType: "date",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "supplier_type_pty_ltd",
        aliases: ["(PTY) LIMITED", "PTY LTD", "PROPRIETARY LIMITED"],
        sourcePath: "semantic.companyType",
        semanticKey: "companyTypePtyLtd",
        fieldType: "checkbox",
        required: false,
        placementPreference: "inline_anchor",
      },
    ],
  },
  SBD4: {
    formId: "SBD4",
    fields: [
      {
        fieldId: "company_name",
        aliases: ["NAME OF BIDDER", "BIDDER NAME", "COMPANY NAME"],
        sourcePath: "contractor.companyName",
        semanticKey: "companyName",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "director_name",
        aliases: [
          "FULL NAME OF BIDDER OR HIS OR HER REPRESENTATIVE",
          "FULL NAME OF REPRESENTATIVE",
        ],
        sourcePath: "semantic.signatureName",
        semanticKey: "signatureName",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "relationship_declaration",
        aliases: ["DO YOU, OR ANY PERSON CONNECTED WITH THE BIDDER", "RELATIONSHIP DECLARATION"],
        sourcePath: "semantic.relationshipDeclaration",
        semanticKey: "relationshipDeclaration",
        fieldType: "text",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "signature_name",
        aliases: ["FULL NAME OF BIDDER OR HIS OR HER REPRESENTATIVE", "SIGNATURE"],
        sourcePath: "semantic.signatureName",
        semanticKey: "signatureName",
        fieldType: "signature",
        required: true,
        placementPreference: "below_anchor",
      },
      {
        fieldId: "signature_role",
        aliases: ["CAPACITY", "ROLE", "POSITION"],
        sourcePath: "semantic.signatureRole",
        semanticKey: "signatureRole",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "date",
        aliases: ["DATE SIGNED", "SIGNATURE DATE", "FORM DATE", "DATE"],
        sourcePath: "semantic.today",
        semanticKey: "today",
        fieldType: "date",
        required: true,
        placementPreference: "right_of_anchor",
      },
    ],
  },
  "SBD6.1": {
    formId: "SBD6.1",
    fields: [
      {
        fieldId: "company_name",
        aliases: ["NAME OF BIDDER", "BIDDER NAME", "COMPANY NAME"],
        sourcePath: "contractor.companyName",
        semanticKey: "companyName",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "registration_number",
        aliases: ["REGISTRATION NUMBER", "COMPANY REG NUMBER", "CK NUMBER", "ENTITY REGISTRATION"],
        sourcePath: "contractor.regNumber",
        semanticKey: "regNumber",
        fieldType: "text",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "bbbee_level",
        aliases: ["B-BBEE STATUS LEVEL", "BEE STATUS LEVEL", "B-BBEE LEVEL"],
        sourcePath: "contractor.bbbeeLevel",
        semanticKey: "bbbeeLevel",
        fieldType: "text",
        required: false,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "bbbee_issue_date",
        aliases: ["B-BBEE ISSUE DATE", "B-BBEE CERTIFICATE ISSUE DATE", "DATE OF ISSUE", "ISSUE DATE"],
        sourcePath: "contractor.bbbeeIssueDate",
        semanticKey: "bbbeeIssueDate",
        fieldType: "date",
        required: false,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "signature_name",
        aliases: ["SIGNATURE", "SIGNATURE OF BIDDER"],
        sourcePath: "semantic.signatureName",
        semanticKey: "signatureName",
        fieldType: "signature",
        required: true,
        placementPreference: "right_of_anchor",
      },
      {
        fieldId: "date",
        aliases: ["DATE SIGNED", "SIGNATURE DATE", "FORM DATE", "DATE"],
        sourcePath: "semantic.today",
        semanticKey: "today",
        fieldType: "date",
        required: true,
        placementPreference: "right_of_anchor",
      },
    ],
  },
};
