import { getCapabilityRegistry } from './capabilityRegistry';
import { normalizeCapabilityKey, normalizeCapabilityKeys, toCapabilitySet, type CapabilityKey, type CapabilitySubject } from './capabilityTypes';

const getWorkspaceType = (subject: CapabilitySubject): CapabilitySubject['workspaceType'] => subject.workspace?.type ?? subject.workspaceType;
const getWorkspaceOwnerId = (subject: CapabilitySubject): string | undefined => subject.workspaceOwnerId;
export function resolveCapabilities(subject: CapabilitySubject = {}): readonly CapabilityKey[] { const explicitCapabilities = normalizeCapabilityKeys(subject.capabilities); const explicitSet = toCapabilitySet(explicitCapabilities); const resolved: CapabilityKey[] = []; const seen = new Set<CapabilityKey>(); const workspaceType = getWorkspaceType(subject); for (const definition of getCapabilityRegistry()) { const roleMatch = Boolean(subject.role && definition.defaultRoles.includes(subject.role)); const workspaceMatch = Boolean(workspaceType && definition.workspaceTypes?.includes(workspaceType)); const ownerMatch = Boolean(definition.ownerGranted && subject.uid && getWorkspaceOwnerId(subject) && subject.uid === getWorkspaceOwnerId(subject)); if (roleMatch || workspaceMatch || ownerMatch || explicitSet.has(definition.key)) { if (!seen.has(definition.key)) { seen.add(definition.key); resolved.push(definition.key); } } } for (const capability of explicitCapabilities) { if (!seen.has(capability)) { seen.add(capability); resolved.push(capability); } } return Object.freeze(resolved); }
export function hasCapability(subject: CapabilitySubject, capability: CapabilityKey | unknown): boolean { const normalizedCapability = normalizeCapabilityKey(capability); if (!normalizedCapability) { return false; } return resolveCapabilities(subject).includes(normalizedCapability); }
export function hasAnyCapability(subject: CapabilitySubject, capabilities: readonly unknown[]): boolean { const normalizedCapabilities = normalizeCapabilityKeys(capabilities); if (!normalizedCapabilities.length) { return false; } const resolved = toCapabilitySet(resolveCapabilities(subject)); return normalizedCapabilities.some((capability) => resolved.has(capability)); }
export function canAccessFeature(subject: CapabilitySubject, capability: CapabilityKey | readonly unknown[]): boolean { return Array.isArray(capability) ? hasAnyCapability(subject, capability) : hasCapability(subject, capability); }
export function hasAllCapabilities(subject: CapabilitySubject, capabilities: readonly unknown[]): boolean { const normalizedCapabilities = normalizeCapabilityKeys(capabilities); if (!normalizedCapabilities.length) { return false; } const resolved = toCapabilitySet(resolveCapabilities(subject)); return normalizedCapabilities.every((capability) => resolved.has(capability)); }
