import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function generateSimplePack(deal: any, contractor: any) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([600, 800]);

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  let y = 750;

  const drawText = (text: string, size = 12) => {
    page.drawText(text, {
      x: 50,
      y,
      size,
      font,
      color: rgb(0, 0, 0),
    });
    y -= size + 6;
  };

  drawText("TORQUE EMPIRE PTY LTD", 18);
  drawText("AI TENDER PACK GENERATOR", 12);
  drawText("TENDER PACK", 14);
  y -= 10;

  drawText(`Deal ID: ${deal?.id || "N/A"}`);
  drawText(`Title: ${deal?.title || "N/A"}`);
  drawText(`Status: ${deal?.status || "N/A"}`);

  y -= 15;

  drawText("Contractor Details:", 13);
  drawText(`ID: ${contractor?.id || "N/A"}`);
  drawText(`Name: ${contractor?.name || "N/A"}`);
  drawText(`Company: ${contractor?.companyName || "N/A"}`);
  drawText(`Email: ${contractor?.email || "N/A"}`);
  drawText(`Phone: ${contractor?.phone || "N/A"}`);
  drawText(`Registration: ${contractor?.registrationNumber || "N/A"}`);

  y -= 20;

  drawText("Analysis Summary:", 13);
  drawText(`Score: ${deal?.analysis?.score ?? 0}`);
  drawText(`Risk: ${deal?.analysis?.risk ?? "UNKNOWN"}`);

  y -= 10;

  drawText("Missing Requirements:", 13);

  (deal?.analysis?.missing || []).forEach((item: string) => {
    drawText(`- ${item}`);
  });

  y -= 20;

  drawText("Generated by Torque Empire AI Pro CRM", 10);

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}
