import type { BoundingBoxFieldDefinition } from "./types";

const singleLineHeight = 14.52;

export const SBD1_BOUNDING_BOXES: Record<string, BoundingBoxFieldDefinition> = {
  company_name: {
    fieldId: "company_name",
    page: 0,
    xMin: 144.02,
    xMax: 567.09,
    yMin: 426.67,
    yMax: 441.19,
    alignment: "left",
    lineSpacing: 10,
    maxFontSize: 10,
    minFontSize: 7.5,
    multiline: false,
  },
  postal_address: {
    fieldId: "postal_address",
    page: 0,
    xMin: 144.02,
    xMax: 567.09,
    yMin: 409.15,
    yMax: 423.67,
    alignment: "left",
    lineSpacing: 9.5,
    maxFontSize: 9.5,
    minFontSize: 7,
    multiline: true,
  },
  street_address: {
    fieldId: "street_address",
    page: 0,
    xMin: 144.02,
    xMax: 567.09,
    yMin: 391.63,
    yMax: 406.27,
    alignment: "left",
    lineSpacing: 9.5,
    maxFontSize: 9.5,
    minFontSize: 7,
    multiline: true,
  },
  registration_number: {
    fieldId: "registration_number",
    page: 0,
    xMin: 144.02,
    xMax: 567.09,
    yMin: 269.94,
    yMax: 284.62,
    alignment: "left",
    lineSpacing: 9,
    maxFontSize: 9.25,
    minFontSize: 7,
    multiline: false,
  },
  vat_number: {
    fieldId: "vat_number",
    page: 0,
    xMin: 144.02,
    xMax: 567.09,
    yMin: 241.25,
    yMax: 263.09,
    alignment: "left",
    lineSpacing: 9,
    maxFontSize: 9.25,
    minFontSize: 7,
    multiline: true,
  },
  tax_pin: {
    fieldId: "tax_pin",
    page: 0,
    xMin: 227.57,
    xMax: 297.65,
    yMin: 182.54,
    yMax: 197.08,
    alignment: "center",
    lineSpacing: 9,
    maxFontSize: 9.5,
    minFontSize: 7,
    multiline: false,
  },
  bbbee_status: {
    fieldId: "bbbee_status",
    page: 0,
    xMin: 148,
    xMax: 348,
    yMin: 132,
    yMax: 146,
    alignment: "left",
    lineSpacing: 9,
    maxFontSize: 9.25,
    minFontSize: 7,
    multiline: false,
  },
  foreign_supplier_yes: {
    fieldId: "foreign_supplier_yes",
    page: 0,
    xMin: 170,
    xMax: 180,
    yMin: 164,
    yMax: 174,
    alignment: "center",
    lineSpacing: singleLineHeight,
    maxFontSize: 10,
    minFontSize: 10,
    multiline: false,
    isCheckbox: true,
  },
  foreign_supplier_no: {
    fieldId: "foreign_supplier_no",
    page: 0,
    xMin: 208,
    xMax: 218,
    yMin: 164,
    yMax: 174,
    alignment: "center",
    lineSpacing: singleLineHeight,
    maxFontSize: 10,
    minFontSize: 10,
    multiline: false,
    isCheckbox: true,
  },
  supplier_type_pty_ltd: {
    fieldId: "supplier_type_pty_ltd",
    page: 0,
    xMin: 148,
    xMax: 158,
    yMin: 108,
    yMax: 118,
    alignment: "center",
    lineSpacing: singleLineHeight,
    maxFontSize: 10,
    minFontSize: 10,
    multiline: false,
    isCheckbox: true,
  },
};
