import type { BoundingBoxTemplateDefinition } from "./types";

export const SBD4_BOUNDING_BOXES: BoundingBoxTemplateDefinition = {
  formId: "SBD4",
  templateVersion: "sbd4-sa-v1",
  fields: {
    company_name: {
      fieldId: "company_name",
      page: 0,
      xMin: 111,
      xMax: 431,
      yMin: 602,
      yMax: 618,
      alignment: "left",
      lineHeight: 10,
      padding: 1.5,
      maxLines: 1,
      overflowBehavior: "scale",
      maxFontSize: 9.5,
      minFontSize: 7.5,
      multiline: false,
      fieldVersion: "1.0.0",
    },
    director_name: {
      fieldId: "director_name",
      page: 1,
      xMin: 276,
      xMax: 523,
      yMin: 727,
      yMax: 743,
      alignment: "left",
      lineHeight: 10,
      padding: 1.5,
      maxLines: 1,
      overflowBehavior: "scale",
      maxFontSize: 9.5,
      minFontSize: 7.5,
      multiline: false,
      fieldVersion: "1.0.0",
    },
    relationship_declaration: {
      fieldId: "relationship_declaration",
      page: 1,
      xMin: 454,
      xMax: 532,
      yMin: 265,
      yMax: 281,
      alignment: "left",
      lineHeight: 10,
      padding: 1,
      maxLines: 1,
      overflowBehavior: "truncate",
      maxFontSize: 9.5,
      minFontSize: 7.5,
      multiline: false,
      fieldVersion: "1.0.0",
    },
    signature_name: {
      fieldId: "signature_name",
      page: 3,
      xMin: 246,
      xMax: 523,
      yMin: 70,
      yMax: 86,
      alignment: "left",
      lineHeight: 10,
      padding: 1,
      maxLines: 1,
      overflowBehavior: "scale",
      maxFontSize: 10,
      minFontSize: 7.5,
      multiline: false,
      fieldVersion: "1.0.1",
    },
    signature_role: {
      fieldId: "signature_role",
      page: 1,
      xMin: 276,
      xMax: 523,
      yMin: 638,
      yMax: 660,
      alignment: "left",
      lineHeight: 8.75,
      padding: 1,
      maxLines: 2,
      overflowBehavior: "wrap",
      maxFontSize: 9.25,
      minFontSize: 6.75,
      multiline: true,
      fieldVersion: "1.0.2",
    },
  },
};
