import type { EmpirePdfTemplateDefinition } from "./types";

export const SBD1_TEMPLATE: EmpirePdfTemplateDefinition = {
  templateKey: "sbd1",
  formId: "SBD1",
  pdfRelativePath: "src/lib/pdfs/templates/tender-packs/sbd1.pdf",
  pageMappings: [0],
  fields: [
    {
      fieldId: "company_name",
      pageIndex: 0,
      anchorText: "NAME OF BIDDER",
      fieldType: "text",
      criticality: "critical",
      semanticKey: "companyName",
      placement: "below",
      alignment: "left",
      textBounds: { width: 240, height: 14 },
      fallback: { pageIndex: 0, x: 148, y: 431.2, width: 415.5, height: 14 },
      maxFontSize: 10,
      minFontSize: 7.5,
    },
    {
      fieldId: "postal_address",
      pageIndex: 0,
      anchorText: "POSTAL ADDRESS",
      fieldType: "text",
      criticality: "important",
      semanticKey: "postalAddress",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 24 },
      multiline: true,
      lineHeight: 10,
      fallback: { pageIndex: 0, x: 148, y: 413.7, width: 415.5, height: 24 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "street_address",
      pageIndex: 0,
      anchorText: "STREET ADDRESS",
      fieldType: "text",
      criticality: "important",
      semanticKey: "streetAddress",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 24 },
      multiline: true,
      lineHeight: 10,
      fallback: { pageIndex: 0, x: 148, y: 396.2, width: 415.5, height: 24 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "registration_number",
      pageIndex: 0,
      anchorText: "REGISTRATION NUMBER",
      fieldType: "text",
      criticality: "critical",
      semanticKey: "regNumber",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 148, y: 272, width: 415.5, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "telephone",
      pageIndex: 0,
      anchorText: "TELEPHONE NUMBER",
      fieldType: "text",
      criticality: "important",
      semanticKey: "phone",
      placement: "right",
      alignment: "left",
      textBounds: { width: 130, height: 14 },
      fallback: { pageIndex: 0, x: 239, y: 380.7, width: 207, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "email",
      pageIndex: 0,
      anchorText: "E-MAIL ADDRESS",
      fieldType: "text",
      criticality: "important",
      semanticKey: "email",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 149, y: 290, width: 415.5, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "vat_number",
      pageIndex: 0,
      anchorText: "VAT REGISTRATION NUMBER",
      fieldType: "text",
      criticality: "important",
      semanticKey: "vatNumber",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 148, y: 258, width: 415.5, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "tax_pin",
      pageIndex: 0,
      anchorText: "TAX COMPLIANCE SYSTEM PIN",
      fieldType: "text",
      criticality: "critical",
      semanticKey: "taxPin",
      placement: "right",
      alignment: "left",
      textBounds: { width: 90, height: 14 },
      fallback: { pageIndex: 0, x: 238, y: 186.8, width: 62, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "csd_number",
      pageIndex: 0,
      anchorText: "CENTRAL SUPPLIER DATABASE No",
      fieldType: "text",
      criticality: "important",
      semanticKey: "csdNumber",
      placement: "right",
      alignment: "left",
      textBounds: { width: 120, height: 14 },
      fallback: { pageIndex: 0, x: 436, y: 185.8, width: 131, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "foreign_supplier_yes",
      pageIndex: 0,
      anchorText: "ARE YOU A FOREIGN BASED SUPPLIER",
      fieldType: "checkbox",
      criticality: "optional",
      semanticKey: "foreignSupplierYes",
      placement: "below",
      alignment: "center",
      textBounds: { width: 10, height: 10 },
      checkboxGlyph: "✓",
      fallback: { pageIndex: 0, x: 170, y: 164, width: 10, height: 10 },
      maxFontSize: 10,
      minFontSize: 10,
    },
    {
      fieldId: "foreign_supplier_no",
      pageIndex: 0,
      anchorText: "ARE YOU A FOREIGN BASED SUPPLIER",
      fieldType: "checkbox",
      criticality: "optional",
      semanticKey: "foreignSupplierNo",
      placement: "right",
      alignment: "center",
      textBounds: { width: 10, height: 10 },
      checkboxGlyph: "✓",
      fallback: { pageIndex: 0, x: 208, y: 164, width: 10, height: 10 },
      maxFontSize: 10,
      minFontSize: 10,
    },
    {
      fieldId: "bbbee_status",
      pageIndex: 0,
      anchorText: "B-BBEE STATUS LEVEL VERIFICATION CERTIFICATE",
      fieldType: "text",
      criticality: "important",
      semanticKey: "bbbeeLevel",
      placement: "below",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 148, y: 136, width: 200, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "supplier_type_pty_ltd",
      pageIndex: 0,
      anchorText: "PTY LTD",
      fieldType: "checkbox",
      criticality: "optional",
      semanticKey: "companyTypePtyLtd",
      placement: "inline",
      alignment: "center",
      textBounds: { width: 10, height: 10 },
      checkboxGlyph: "X",
      fallback: { pageIndex: 0, x: 148, y: 108, width: 10, height: 10 },
      maxFontSize: 10,
      minFontSize: 10,
    },
    {
      fieldId: "signature_name",
      pageIndex: 0,
      anchorText: "SIGNATURE OF BIDDER",
      fieldType: "signature",
      criticality: "critical",
      semanticKey: "signatureName",
      placement: "below",
      alignment: "left",
      textBounds: { width: 220, height: 14 },
      fallback: { pageIndex: 0, x: 150, y: 82, width: 220, height: 14 },
      maxFontSize: 10,
      minFontSize: 7.5,
    },
    {
      fieldId: "date",
      pageIndex: 0,
      anchorText: "DATE",
      fieldType: "date",
      criticality: "important",
      semanticKey: "today",
      placement: "below",
      alignment: "left",
      textBounds: { width: 120, height: 14 },
      fallback: { pageIndex: 0, x: 430, y: 82, width: 120, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
  ],
};
