import type { EmpirePdfTemplateDefinition } from "./types";

export const SBD4_TEMPLATE: EmpirePdfTemplateDefinition = {
  templateKey: "sbd4",
  formId: "SBD4",
  pdfRelativePath: "src/lib/pdfs/templates/tender-packs/sbd4.pdf",
  pageMappings: [0, 1, 2],
  fields: [
    {
      fieldId: "company_name",
      pageIndex: 0,
      anchorText: "Name of bidder",
      fieldType: "text",
      semanticKey: "companyName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 111, y: 604, width: 320, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "director_name",
      pageIndex: 0,
      anchorText: "Full name of bidder or his or her representative",
      fieldType: "text",
      semanticKey: "signatureName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 111, y: 512, width: 300, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "relationship_declaration",
      pageIndex: 1,
      anchorText: "Do you, or any person connected with the bidder",
      fieldType: "text",
      semanticKey: "relationshipDeclaration",
      placement: "below",
      alignment: "left",
      textBounds: { width: 80, height: 14 },
      fallback: { pageIndex: 1, x: 454, y: 267, width: 78, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "signature_name",
      pageIndex: 2,
      anchorText: "Full name of bidder or his or her representative",
      fieldType: "signature",
      semanticKey: "signatureName",
      placement: "below",
      alignment: "left",
      textBounds: { width: 180, height: 14 },
      fallback: { pageIndex: 2, x: 278, y: 352, width: 170, height: 14 },
      maxFontSize: 10,
      minFontSize: 7.5,
    },
    {
      fieldId: "signature_role",
      pageIndex: 2,
      anchorText: "Capacity",
      fieldType: "text",
      semanticKey: "signatureRole",
      placement: "right",
      alignment: "left",
      textBounds: { width: 160, height: 14 },
      fallback: { pageIndex: 2, x: 278, y: 328, width: 160, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7,
    },
    {
      fieldId: "date",
      pageIndex: 2,
      anchorText: "Date",
      fieldType: "date",
      semanticKey: "today",
      placement: "right",
      alignment: "left",
      textBounds: { width: 100, height: 14 },
      fallback: { pageIndex: 2, x: 282, y: 399, width: 120, height: 14 },
      maxFontSize: 10,
      minFontSize: 7.5,
    },
  ],
};
