import type { EmpirePdfTemplateDefinition } from "./types";

export const SBD4_TEMPLATE: EmpirePdfTemplateDefinition = {
  templateKey: "sbd4",
  formId: "SBD4",
  templateVersion: "sbd4-sa-v1",
  pdfRelativePath: "src/lib/pdfs/templates/tender-packs/sbd4.pdf",
  pageMappings: [0, 1, 2, 3],
  fields: [
    {
      fieldId: "company_name",
      pageIndex: 0,
      anchorText: "Name of bidder",
      fieldType: "text",
      semanticKey: "companyName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 111, y: 604, width: 320, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
      overflowBehavior: "scale",
      maxLines: 1,
      padding: 1.5,
      fieldVersion: "1.0.0",
    },
    {
      fieldId: "director_name",
      pageIndex: 1,
      anchorText: "Full name of bidder or his or her representative",
      fieldType: "text",
      semanticKey: "signatureName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 1, x: 276, y: 731, width: 247, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
      overflowBehavior: "scale",
      maxLines: 1,
      padding: 1.5,
      fieldVersion: "1.0.0",
    },
    {
      fieldId: "relationship_declaration",
      pageIndex: 1,
      anchorText: "Do you, or any person connected with the bidder",
      fieldType: "text",
      semanticKey: "relationshipDeclaration",
      placement: "below",
      alignment: "left",
      textBounds: { width: 80, height: 14 },
      fallback: { pageIndex: 1, x: 454, y: 267, width: 78, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
      overflowBehavior: "truncate",
      maxLines: 1,
      padding: 1,
      fieldVersion: "1.0.0",
    },
    {
      fieldId: "signature_name",
      pageIndex: 3,
      anchorText: "I, THE UNDERSIGNED (NAME)",
      fieldType: "signature",
      semanticKey: "signatureName",
      placement: "below",
      alignment: "left",
      textBounds: { width: 180, height: 14 },
      fallback: { pageIndex: 3, x: 246, y: 74, width: 277, height: 14 },
      maxFontSize: 10,
      minFontSize: 7.5,
      overflowBehavior: "scale",
      maxLines: 1,
      padding: 1,
      fieldVersion: "1.0.0",
    },
    {
      fieldId: "signature_role",
      pageIndex: 1,
      anchorText: "Position occupied in the Company",
      fieldType: "text",
      semanticKey: "signatureRole",
      placement: "right",
      alignment: "left",
      textBounds: { width: 247, height: 20 },
      fallback: { pageIndex: 1, x: 276, y: 642, width: 247, height: 20 },
      maxFontSize: 9.5,
      minFontSize: 7,
      overflowBehavior: "scale",
      maxLines: 1,
      padding: 1,
      fieldVersion: "1.0.0",
    },
  ],
};
