import type { EmpirePdfTemplateDefinition } from "./types";

export const SBD61_TEMPLATE: EmpirePdfTemplateDefinition = {
  templateKey: "sbd6",
  formId: "SBD6.1",
  pdfRelativePath: "src/lib/pdfs/templates/tender-packs/sbd6.pdf",
  pageMappings: [0],
  fields: [
    {
      fieldId: "company_name",
      pageIndex: 0,
      anchorText: "Name of bidder",
      fieldType: "text",
      semanticKey: "companyName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 260, height: 14 },
      fallback: { pageIndex: 0, x: 140, y: 515, width: 320, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "registration_number",
      pageIndex: 0,
      anchorText: "Registration number",
      fieldType: "text",
      semanticKey: "regNumber",
      placement: "right",
      alignment: "left",
      textBounds: { width: 220, height: 14 },
      fallback: { pageIndex: 0, x: 140, y: 492, width: 220, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "bbbee_level",
      pageIndex: 0,
      anchorText: "B-BBEE Status level",
      fieldType: "text",
      semanticKey: "bbbeeLevel",
      placement: "right",
      alignment: "left",
      textBounds: { width: 220, height: 14 },
      fallback: { pageIndex: 0, x: 140, y: 422, width: 220, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "signature_name",
      pageIndex: 0,
      anchorText: "Signature",
      fieldType: "signature",
      semanticKey: "signatureName",
      placement: "right",
      alignment: "left",
      textBounds: { width: 220, height: 14 },
      fallback: { pageIndex: 0, x: 140, y: 210, width: 320, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
    {
      fieldId: "date",
      pageIndex: 0,
      anchorText: "Date signed",
      fieldType: "date",
      semanticKey: "today",
      placement: "right",
      alignment: "left",
      textBounds: { width: 100, height: 14 },
      fallback: { pageIndex: 0, x: 420, y: 210, width: 120, height: 14 },
      maxFontSize: 9.5,
      minFontSize: 7.5,
    },
  ],
};
