import { readFile } from "node:fs/promises";
import path from "node:path";
import { PDFDocument, StandardFonts, rgb, type PDFImage, type PDFPage, type PDFFont } from "pdf-lib";
import { TORQUE_EMPIRE_BRAND, TORQUE_EMPIRE_BRAND_ASSETS } from "@/lib/branding/identity";
import { TORQUE_EMPIRE_COMPANY_PROFILE, getCorporateEmail } from "@/lib/corporate/companyProfile";
import type { ConsolidatedHygieneClientPackData } from "@/lib/hygiene/hygieneConsolidatedPack";
import type { HygieneClient, HygieneCollection, HygieneComplianceDocument, HygieneEvidencePhoto, HygieneManifest, HygieneSignature, HygieneSite } from "@/types/hygiene";

export type HygienePdfDocumentData = {
  manifest: HygieneManifest;
  collection: HygieneCollection;
  client: HygieneClient;
  site: HygieneSite;
  signatures?: HygieneSignature[];
  disposalEvidence?: Array<HygieneEvidencePhoto | HygieneComplianceDocument>;
  generatedAt?: string;
};

export type ConsolidatedCertificateAttachment = {
  evidenceId: string;
  manifestId: string;
  collectionId: string;
  bytes: Uint8Array;
};

type PdfKit = {
  document: PDFDocument;
  fonts: { regular: PDFFont; bold: PDFFont };
  brandImage: PDFImage | null;
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const HEADER_HEIGHT = 112;
const HEADER_BOTTOM = PAGE_HEIGHT - HEADER_HEIGHT;
const BODY_TOP = HEADER_BOTTOM - 22;
const FOOTER_TOP = 68;
const BODY_BOTTOM = FOOTER_TOP + 20;
const ROW_PADDING_X = 8;
const ROW_PADDING_Y = 4;
const LINE_HEIGHT_FACTOR = 1.25;
const NAVY = rgb(7 / 255, 17 / 255, 31 / 255);
const BLUE = rgb(11 / 255, 47 / 255, 87 / 255);
const GOLD = rgb(200 / 255, 162 / 255, 74 / 255);
const WHITE = rgb(1, 1, 1);
const MUTED = rgb(91 / 255, 104 / 255, 120 / 255);
const BORDER = rgb(217 / 255, 226 / 255, 236 / 255);
const SURFACE = rgb(244 / 255, 247 / 255, 251 / 255);

export const TORQUE_EMPIRE_HYGIENE_PDF_BRAND = {
  divisionName: "Torque Empire - Hygiene Solutions",
  documentGenerator: "Generated by TEOS on behalf of Torque Empire (Pty) Ltd",
  approvedLetterheadAsset: TORQUE_EMPIRE_BRAND_ASSETS.businessLetterheadPng,
  fallbackLogoAsset: TORQUE_EMPIRE_BRAND_ASSETS.logoPrimaryPng,
  colors: {
    navy: TORQUE_EMPIRE_BRAND.colors.navy,
    gold: TORQUE_EMPIRE_BRAND.colors.gold,
    white: TORQUE_EMPIRE_BRAND.colors.white,
  },
} as const;

const INTERNAL_LABELS = [
  "staff-only",
  "staff only",
  "internal teos id",
  "audit internal",
  "internal scoring",
  "confidential system metadata",
  "admin override",
  "device info",
  "gps",
  "storagepath",
  "storage path",
  "fileurl",
  "file url",
  "signaturedataurl",
  "uid",
];

function text(value: unknown, fallback = "Pending"): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function dateText(value: string | null | undefined): string {
  return value ? value.slice(0, 10) : "Pending";
}

function normalizeAddressPart(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[^\x00-\x7F]/g, "")
    .replace(/\s+/g, " ")
    .replace(/[.,]+$/g, "")
    .trim()
    .toLowerCase();
}

export function buildHygieneSiteLabel(site: HygieneSite): string {
  const parts = [site.siteName, site.address];
  const addressKey = normalizeAddressPart(site.address);

  for (const value of [site.suburb, site.city]) {
    const key = normalizeAddressPart(value);
    if (key && !addressKey.includes(key)) parts.push(value);
  }

  return parts.filter((value) => typeof value === "string" && value.trim()).join(", ");
}

function slug(value: string): string {
  const cleaned = text(value, "Pending")
    .normalize("NFKD")
    .replace(/[^\x00-\x7F]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return cleaned || "Pending";
}

export async function loadTorqueEmpirePdfBrandImage(document: PDFDocument): Promise<PDFImage | null> {
  try {
    const letterheadBytes = await readFile(path.join(process.cwd(), "public", "corporate", "letterhead", "torque-empire-business-letterhead.png"));
    return await document.embedPng(letterheadBytes);
  } catch {
    try {
      const logoBytes = await readFile(path.join(process.cwd(), "public", "corporate", "logo", "torque-empire-primary.png"));
      return await document.embedPng(logoBytes);
    } catch {
      return null;
    }
  }
}

export function buildPdfContentDisposition(disposition: "inline" | "attachment", filename: string): string {
  const safeName = slug(filename.replace(/\.pdf$/i, "")).slice(0, 150) + ".pdf";
  return `${disposition}; filename="${safeName}"; filename*=UTF-8''${encodeURIComponent(safeName)}`;
}

async function createKit(): Promise<PdfKit> {
  const document = await PDFDocument.create();
  document.setTitle("Torque Empire Hygiene Waste Manifest");
  document.setAuthor("TEOS on behalf of Torque Empire (Pty) Ltd");
  document.setCreator("TEOS on behalf of Torque Empire (Pty) Ltd");
  document.setProducer("TEOS document generation");
  document.setSubject("Waste manifest generated by TEOS on behalf of Torque Empire (Pty) Ltd");
  document.setKeywords(["Torque Empire", "TEOS", "Hygiene Solutions", "Waste Manifest"]);

  return {
    document,
    fonts: {
      regular: await document.embedFont(StandardFonts.Helvetica),
      bold: await document.embedFont(StandardFonts.HelveticaBold),
    },
    brandImage: await loadTorqueEmpirePdfBrandImage(document),
  };
}

function drawText(page: PDFPage, value: string, x: number, y: number, options: { size?: number; font: PDFFont; color?: ReturnType<typeof rgb>; maxWidth?: number }) {
  page.drawText(value, { x, y, size: options.size ?? 10, font: options.font, color: options.color ?? NAVY, maxWidth: options.maxWidth });
}

function wrapText(value: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const paragraph of text(value).split(/\r?\n/)) {
    const words = paragraph.split(/\s+/).filter(Boolean);
    let line = "";
    for (const word of words) {
      const candidate = line ? line + " " + word : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        line = candidate;
        continue;
      }
      if (line) lines.push(line);
      if (font.widthOfTextAtSize(word, size) <= maxWidth) {
        line = word;
        continue;
      }
      let fragment = "";
      for (const char of word) {
        const candidateFragment = fragment + char;
        if (font.widthOfTextAtSize(candidateFragment, size) <= maxWidth) {
          fragment = candidateFragment;
        } else {
          if (fragment) lines.push(fragment);
          fragment = char;
        }
      }
      line = fragment;
    }
    lines.push(line || " ");
  }
  return lines;
}

function wrappedTextHeight(value: string, font: PDFFont, size: number, maxWidth: number): number {
  return wrapText(value, font, size, maxWidth).length * size * LINE_HEIGHT_FACTOR;
}

function drawWrappedText(page: PDFPage, value: string, x: number, y: number, options: { size: number; font: PDFFont; color?: ReturnType<typeof rgb>; maxWidth: number }) {
  const lineHeight = options.size * LINE_HEIGHT_FACTOR;
  const lines = wrapText(value, options.font, options.size, options.maxWidth);
  lines.forEach((line, index) => {
    drawText(page, line, x, y - index * lineHeight, { font: options.font, size: options.size, color: options.color, maxWidth: options.maxWidth });
  });
  return lines.length * lineHeight;
}

export function getHygienePdfLayoutForTesting() {
  return {
    page: { width: PAGE_WIDTH, height: PAGE_HEIGHT },
    header: { top: PAGE_HEIGHT, bottom: HEADER_BOTTOM, height: HEADER_HEIGHT },
    body: { top: BODY_TOP, bottom: BODY_BOTTOM },
    footer: { top: FOOTER_TOP, bottom: 0 },
    headerText: {
      division: { top: PAGE_HEIGHT - 36, bottom: PAGE_HEIGHT - 51 },
      title: { top: PAGE_HEIGHT - 57, bottom: PAGE_HEIGHT - 69 },
      subtitle: { top: PAGE_HEIGHT - 76, bottom: PAGE_HEIGHT - 86 },
    },
  };
}

export function drawTorqueEmpireDocumentHeader(page: PDFPage, kit: PdfKit, title: string, subtitle: string) {
  page.drawRectangle({ x: 0, y: HEADER_BOTTOM, width: PAGE_WIDTH, height: HEADER_HEIGHT, color: WHITE });
  page.drawRectangle({ x: 0, y: HEADER_BOTTOM, width: PAGE_WIDTH, height: 7, color: GOLD });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 12, width: PAGE_WIDTH, height: 12, color: NAVY });

  if (kit.brandImage) {
    const scaled = kit.brandImage.scaleToFit(168, 52);
    page.drawImage(kit.brandImage, { x: MARGIN, y: PAGE_HEIGHT - 82, width: scaled.width, height: scaled.height });
  } else {
    drawText(page, TORQUE_EMPIRE_COMPANY_PROFILE.tradingName, MARGIN, PAGE_HEIGHT - 52, { font: kit.fonts.bold, size: 18, color: NAVY });
  }

  const headerX = 330;
  const headerWidth = PAGE_WIDTH - headerX - MARGIN;
  drawWrappedText(page, TORQUE_EMPIRE_HYGIENE_PDF_BRAND.divisionName, headerX, PAGE_HEIGHT - 36, { font: kit.fonts.bold, size: 11.5, color: BLUE, maxWidth: headerWidth });
  drawWrappedText(page, title, headerX, PAGE_HEIGHT - 57, { font: kit.fonts.bold, size: 9.5, color: NAVY, maxWidth: headerWidth });
  drawWrappedText(page, subtitle, headerX, PAGE_HEIGHT - 76, { font: kit.fonts.regular, size: 8, color: MUTED, maxWidth: headerWidth });
}

function drawFooter(page: PDFPage, kit: PdfKit, pageNumber: number) {
  page.drawLine({ start: { x: MARGIN, y: 58 }, end: { x: PAGE_WIDTH - MARGIN, y: 58 }, thickness: 0.8, color: BORDER });
  drawText(page, `${TORQUE_EMPIRE_COMPANY_PROFILE.companyName} | ${TORQUE_EMPIRE_COMPANY_PROFILE.website} | ${getCorporateEmail("info")} | ${TORQUE_EMPIRE_COMPANY_PROFILE.telephone}`, MARGIN, 42, { font: kit.fonts.regular, size: 7.5, color: MUTED, maxWidth: 400 });
  drawText(page, TORQUE_EMPIRE_HYGIENE_PDF_BRAND.documentGenerator, MARGIN, 29, { font: kit.fonts.bold, size: 7.5, color: BLUE, maxWidth: 360 });
  drawText(page, `Page ${pageNumber}`, PAGE_WIDTH - 86, 29, { font: kit.fonts.regular, size: 8, color: MUTED });
}

function addPage(kit: PdfKit, title: string, subtitle: string) {
  const page = kit.document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawTorqueEmpireDocumentHeader(page, kit, title, subtitle);
  drawFooter(page, kit, kit.document.getPageCount());
  return page;
}

function drawSection(page: PDFPage, kit: PdfKit, heading: string, y: number) {
  page.drawRectangle({ x: MARGIN, y: y - 4, width: PAGE_WIDTH - MARGIN * 2, height: 18, color: SURFACE, borderColor: BORDER, borderWidth: 0.5 });
  page.drawRectangle({ x: MARGIN, y: y - 4, width: 4, height: 18, color: GOLD });
  drawText(page, heading, MARGIN + 12, y + 2, { font: kit.fonts.bold, size: 10, color: BLUE });
}

export function measureHygienePdfRowsForTesting(rows: Array<[string, string]>, width: number, fonts: { regular: PDFFont; bold: PDFFont }) {
  const labelWidth = width * 0.32;
  const valueWidth = width - labelWidth - ROW_PADDING_X * 3;
  return rows.map(([label, value]) => {
    const labelHeight = wrappedTextHeight(label, fonts.bold, 8, labelWidth - ROW_PADDING_X * 2);
    const valueHeight = wrappedTextHeight(value, fonts.regular, 8.2, valueWidth - ROW_PADDING_X * 2);
    return Math.max(20, Math.ceil(Math.max(labelHeight, valueHeight) + ROW_PADDING_Y * 2));
  });
}

function drawRows(page: PDFPage, kit: PdfKit, rows: Array<[string, string]>, x: number, y: number, width: number) {
  let cursor = y;
  const labelWidth = width * 0.32;
  const valueX = x + labelWidth + ROW_PADDING_X;
  const valueWidth = width - labelWidth - ROW_PADDING_X;
  const heights = measureHygienePdfRowsForTesting(rows, width, kit.fonts);
  for (const [index, [label, value]] of rows.entries()) {
    const rowHeight = heights[index] ?? 26;
    page.drawRectangle({ x, y: cursor - rowHeight + 9, width, height: rowHeight, borderColor: BORDER, borderWidth: 0.35 });
    const textY = cursor - ROW_PADDING_Y;
    drawWrappedText(page, label, x + ROW_PADDING_X, textY, { font: kit.fonts.bold, size: 8, color: MUTED, maxWidth: labelWidth - ROW_PADDING_X * 2 });
    drawWrappedText(page, value, valueX + ROW_PADDING_X, textY, { font: kit.fonts.regular, size: 8.2, color: NAVY, maxWidth: valueWidth - ROW_PADDING_X * 2 });
    cursor -= rowHeight;
  }
  return cursor;
}

function requiredRowsHeight(rows: Array<[string, string]>, width: number, fonts: { regular: PDFFont; bold: PDFFont }) {
  return measureHygienePdfRowsForTesting(rows, width, fonts).reduce((total, height) => total + height, 0);
}

function publicSignatureRows(signatures: HygieneSignature[] | undefined): Array<[string, string]> {
  if (!signatures?.length) return [["Client representative", "Pending"], ["Signature date", "Pending"]];
  return signatures.map((signature) => [`${signature.representativeName} (${signature.representativePosition})`, dateText(signature.capturedAt)]);
}

function publicCertificateSummary(evidence: Array<HygieneEvidencePhoto | HygieneComplianceDocument> | undefined, manifest: HygieneManifest): string {
  if (manifest.disposalCertificateNo && !/pending/i.test(manifest.disposalCertificateNo)) return manifest.disposalCertificateNo;
  const certificate = evidence?.find((item) => "category" in item ? item.category === "Disposal Certificate" : item.documentType === "Disposal Certificates");
  return certificate ? "Certificate evidence attached" : "Certificate evidence not available yet";
}

export function assertClientFacingHygienePdfContent(markers: string[]) {
  const combined = markers.join("\n").toLowerCase();
  const leaked = INTERNAL_LABELS.find((label) => combined.includes(label));
  if (leaked) throw new Error(`Client-facing Hygiene PDF contains restricted internal marker: ${leaked}`);
}

function ensureBodySpace(kit: PdfKit, currentPage: PDFPage, y: number, title: string, subtitle: string, requiredHeight: number) {
  if (y - requiredHeight >= BODY_BOTTOM) return { page: currentPage, y };
  return { page: addPage(kit, title, subtitle), y: BODY_TOP };
}

function drawRowsSection(kit: PdfKit, page: PDFPage, heading: string, rows: Array<[string, string]>, y: number, title: string, subtitle: string) {
  const width = PAGE_WIDTH - MARGIN * 2;
  const requiredHeight = 18 + 8 + requiredRowsHeight(rows, width, kit.fonts);
  const ready = ensureBodySpace(kit, page, y, title, subtitle, requiredHeight);
  drawSection(ready.page, kit, heading, ready.y);
  const nextY = drawRows(ready.page, kit, rows, MARGIN, ready.y - 18, width) - 6;
  return { page: ready.page, y: nextY };
}

function drawManifestBody(kit: PdfKit, page: PDFPage, data: HygienePdfDocumentData) {
  const { manifest, collection, client, site } = data;
  drawText(page, TORQUE_EMPIRE_BRAND.corporateTagline, MARGIN, BODY_TOP, { font: kit.fonts.bold, size: 10.5, color: NAVY, maxWidth: 360 });
  drawText(page, TORQUE_EMPIRE_BRAND.tagline, MARGIN, BODY_TOP - 15, { font: kit.fonts.regular, size: 8.5, color: GOLD, maxWidth: 320 });
  drawText(page, "Waste Manifest", MARGIN, BODY_TOP - 52, { font: kit.fonts.bold, size: 24, color: NAVY });
  drawText(page, `Manifest reference: ${manifest.manifestId}`, MARGIN, BODY_TOP - 73, { font: kit.fonts.bold, size: 11, color: BLUE });

  let y = BODY_TOP - 88;
  let currentPage = page;
  ({ page: currentPage, y } = drawRowsSection(kit, currentPage, "Client and Site", [
    ["Client", client.clientName],
    ["Site", buildHygieneSiteLabel(site)],
    ["Site contact", `${site.contactPerson} | ${site.contactPhone}`],
  ], y, "Waste Manifest", manifest.manifestId));

  ({ page: currentPage, y } = drawRowsSection(kit, currentPage, "Manifest and Waste Stream", [
    ["Collection reference", collection.collectionId],
    ["Waste classification", manifest.wasteClassification],
    ["Waste stream", manifest.wasteType],
    ["Quantity", `${manifest.quantity} ${manifest.unit}`],
    ["Collection date", dateText(manifest.collectionDate)],
  ], y, "Waste Manifest", manifest.manifestId));

  ({ page: currentPage, y } = drawRowsSection(kit, currentPage, "Transport and Chain of Custody", [
    ["Generator registration", manifest.generatorRegistration],
    ["Transport registration", manifest.transportRegistration],
    ["Collected by", manifest.collectedBy],
    ["Vehicle registration", manifest.vehicleRegistration],
    ["Declaration", "Waste stream, quantity, transport and disposal records are presented for client audit and chain-of-custody review."],
  ], y, "Waste Manifest", manifest.manifestId));

  ({ page: currentPage, y } = drawRowsSection(kit, currentPage, "Disposal Facility and Certification", [
    ["Disposal facility", manifest.disposalFacility],
    ["Disposal date", dateText(manifest.disposalDate)],
    ["Certificate reference", publicCertificateSummary(data.disposalEvidence, manifest)],
    ["Manifest status", manifest.status],
  ], y, "Waste Manifest", manifest.manifestId));

  drawRowsSection(kit, currentPage, "Signatures and Dates", publicSignatureRows(data.signatures), y, "Waste Manifest", manifest.manifestId);
}

function drawClientPackCover(page: PDFPage, kit: PdfKit, data: HygienePdfDocumentData) {
  const { manifest, client, site } = data;
  page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: PAGE_HEIGHT, color: WHITE });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 160, width: PAGE_WIDTH, height: 160, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 166, width: PAGE_WIDTH, height: 6, color: GOLD });
  if (kit.brandImage) {
    const scaled = kit.brandImage.scaleToFit(190, 70);
    page.drawImage(kit.brandImage, { x: MARGIN, y: PAGE_HEIGHT - 116, width: scaled.width, height: scaled.height });
  } else {
    drawText(page, TORQUE_EMPIRE_COMPANY_PROFILE.tradingName, MARGIN, PAGE_HEIGHT - 92, { font: kit.fonts.bold, size: 22, color: WHITE });
  }
  drawText(page, TORQUE_EMPIRE_HYGIENE_PDF_BRAND.divisionName, MARGIN, 590, { font: kit.fonts.bold, size: 20, color: NAVY });
  drawText(page, "Client Compliance Pack", MARGIN, 560, { font: kit.fonts.bold, size: 30, color: BLUE });
  drawText(page, TORQUE_EMPIRE_BRAND.corporateTagline, MARGIN, 535, { font: kit.fonts.bold, size: 11, color: NAVY, maxWidth: 420 });
  drawText(page, TORQUE_EMPIRE_BRAND.tagline, MARGIN, 517, { font: kit.fonts.regular, size: 10, color: GOLD, maxWidth: 420 });

  drawRows(page, kit, [
    ["Client", client.clientName],
    ["Site", buildHygieneSiteLabel(site)],
    ["Waste manifest reference", manifest.manifestId],
    ["Collection reference", manifest.collectionId],
    ["Generated", dateText(data.generatedAt ?? new Date().toISOString())],
  ], MARGIN, 468, PAGE_WIDTH - MARGIN * 2);

  drawSection(page, kit, "Document Index", 296);
  const hasCertificate = data.disposalEvidence?.some((item) => "category" in item ? item.category === "Disposal Certificate" : item.documentType === "Disposal Certificates");
  drawRows(page, kit, [
    ["1", "Torque Empire branded cover page"],
    ["2", "Waste Manifest"],
    ["3", hasCertificate ? "Disposal Certificate / supporting third-party evidence attached unchanged" : "Disposal Certificate / supporting third-party evidence not available yet"],
    ["4", "Compliance declaration / document index"],
  ], MARGIN, 274, PAGE_WIDTH - MARGIN * 2);
  drawFooter(page, kit, 1);
}

function drawComplianceIndex(page: PDFPage, kit: PdfKit, data: HygienePdfDocumentData, certificateIncluded: boolean) {
  drawRowsSection(kit, page, "Compliance Declaration", [
    ["Issued by", "TEOS on behalf of Torque Empire (Pty) Ltd"],
    ["Division", TORQUE_EMPIRE_HYGIENE_PDF_BRAND.divisionName],
    ["Manifest", data.manifest.manifestId],
    ["Certificate evidence", certificateIncluded ? "Attached unchanged from third-party source." : "Not available in this client pack."],
    ["Declaration", "This client pack contains Torque Empire generated manifest records and attached third-party evidence where available. Third-party certificates are included unchanged and retain their original issuer content."],
  ], BODY_TOP, "Compliance Index", data.manifest.manifestId);
}

export function buildHygieneManifestFileName(data: HygienePdfDocumentData): string {
  return `Torque-Empire_Hygiene_${slug(data.client.clientName)}_${slug(data.site.siteName)}_Waste-Manifest_${slug(data.manifest.manifestId)}_${dateText(data.manifest.collectionDate)}.pdf`;
}

export async function generateHygieneManifestPdf(data: HygienePdfDocumentData): Promise<Uint8Array> {
  assertClientFacingHygienePdfContent([
    data.manifest.manifestId,
    data.collection.collectionId,
    data.client.clientName,
    data.site.siteName,
    data.manifest.wasteType,
    data.manifest.disposalFacility,
    data.manifest.disposalCertificateNo,
  ]);
  const kit = await createKit();
  const page = addPage(kit, "Waste Manifest", data.manifest.manifestId);
  drawManifestBody(kit, page, data);
  return kit.document.save();
}


function periodText(period: ConsolidatedHygieneClientPackData["period"]): string {
  if (period.startDate && period.endDate) return period.startDate + " to " + period.endDate;
  if (period.startDate) return "From " + period.startDate;
  if (period.endDate) return "Until " + period.endDate;
  return "All available persisted records";
}

function evidenceStatusText(entry: ConsolidatedHygieneClientPackData["entries"][number]): string {
  if (entry.disposalEvidence.length === 0) return "Pending disposal evidence";
  return entry.disposalEvidence
    .map((item) => item.certificateReference ? item.label + " (" + item.certificateReference + ")" : item.label)
    .join("; ");
}

function drawConsolidatedCover(page: PDFPage, kit: PdfKit, data: ConsolidatedHygieneClientPackData) {
  page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: PAGE_HEIGHT, color: WHITE });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 160, width: PAGE_WIDTH, height: 160, color: NAVY });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 166, width: PAGE_WIDTH, height: 6, color: GOLD });
  if (kit.brandImage) {
    const scaled = kit.brandImage.scaleToFit(190, 70);
    page.drawImage(kit.brandImage, { x: MARGIN, y: PAGE_HEIGHT - 116, width: scaled.width, height: scaled.height });
  } else {
    drawText(page, TORQUE_EMPIRE_COMPANY_PROFILE.tradingName, MARGIN, PAGE_HEIGHT - 92, { font: kit.fonts.bold, size: 22, color: WHITE });
  }
  drawText(page, TORQUE_EMPIRE_HYGIENE_PDF_BRAND.divisionName, MARGIN, 592, { font: kit.fonts.bold, size: 20, color: NAVY });
  drawText(page, "Consolidated Client Manifest Pack", MARGIN, 560, { font: kit.fonts.bold, size: 28, color: BLUE, maxWidth: 480 });
  drawText(page, TORQUE_EMPIRE_BRAND.corporateTagline, MARGIN, 534, { font: kit.fonts.bold, size: 11, color: NAVY, maxWidth: 420 });
  drawText(page, TORQUE_EMPIRE_BRAND.tagline, MARGIN, 516, { font: kit.fonts.regular, size: 10, color: GOLD, maxWidth: 420 });

  drawRows(page, kit, [
    ["Client", data.client.clientName],
    ["Reporting period", periodText(data.period)],
    ["Site filter", data.siteFilter ? buildHygieneSiteLabel(data.siteFilter) : "All selected client sites"],
    ["Generated", dateText(data.generatedAt)],
  ], MARGIN, 466, PAGE_WIDTH - MARGIN * 2);

  drawSection(page, kit, "Summary", 314);
  drawRows(page, kit, [
    ["Sites included", data.summary.sitesIncluded.length ? data.summary.sitesIncluded.join(", ") : "No matching sites"],
    ["Collections", String(data.summary.collectionCount)],
    ["Individual manifests", String(data.summary.manifestCount)],
    ["Disposal evidence items", String(data.summary.evidenceItemCount)],
    ["Total bins / containers", data.summary.totalBins === null ? "Not available" : String(data.summary.totalBins)],
    ["Total recorded waste weight", "Not recorded in persisted evidence"],
    ["Disposal status", "Disposed " + data.summary.disposalStatus.disposed + " | Pending evidence " + data.summary.disposalStatus.pendingEvidence + " | Generated / incomplete " + data.summary.disposalStatus.generatedIncomplete],
  ], MARGIN, 292, PAGE_WIDTH - MARGIN * 2);
  drawFooter(page, kit, 1);
}

function drawConsolidatedRegister(kit: PdfKit, data: ConsolidatedHygieneClientPackData) {
  let page = addPage(kit, "Consolidated Collection Register", data.client.clientName);
  let y = BODY_TOP;
  if (data.entries.length === 0) {
    drawRowsSection(kit, page, "Collection Register", [["Result", "No persisted collection manifests matched the selected client, site and reporting period."]], y, "Consolidated Collection Register", data.client.clientName);
    return;
  }

  for (const entry of data.entries) {
    const rows: Array<[string, string]> = [
      ["Collection reference", entry.collection.collectionId],
      ["Manifest reference", entry.manifest.manifestId],
      ["Site", buildHygieneSiteLabel(entry.site)],
      ["Collection date", dateText(entry.collection.scheduledDate)],
      ["Waste type", entry.manifest.wasteType],
      ["Quantity", entry.manifest.quantity + " " + entry.manifest.unit],
      ["Transport / driver / vehicle", entry.manifest.collectedBy + " | " + entry.manifest.vehicleRegistration],
      ["Disposal facility", entry.disposalEvidence.length > 0 && !/pending|not yet captured/i.test(entry.manifest.disposalFacility) ? entry.manifest.disposalFacility : "Pending disposal evidence"],
      ["Certificate / evidence status", evidenceStatusText(entry)],
      ["Linked certificate reference", entry.disposalEvidence.map((item) => item.certificateReference).filter(Boolean).join(", ") || "Pending disposal evidence"],
    ];
    ({ page, y } = drawRowsSection(kit, page, "Collection " + entry.collection.collectionId, rows, y, "Consolidated Collection Register", data.client.clientName));
  }
}

function drawConsolidatedEvidenceIndex(kit: PdfKit, data: ConsolidatedHygieneClientPackData, attachments: ConsolidatedCertificateAttachment[]) {
  let page = addPage(kit, "Consolidated Evidence Index", data.client.clientName);
  let y = BODY_TOP;
  const attachmentIds = new Set(attachments.map((item) => item.evidenceId));
  for (const entry of data.entries) {
    const evidenceText = entry.disposalEvidence.length
      ? entry.disposalEvidence
          .map((item) => item.evidenceId + ": " + (attachmentIds.has(item.evidenceId) ? "attached unchanged" : "linked record present; source PDF unavailable for append"))
          .join("; ")
      : "Pending disposal evidence";
    ({ page, y } = drawRowsSection(kit, page, "Evidence for " + entry.manifest.manifestId, [
      ["Collection", entry.collection.collectionId],
      ["Manifest", entry.manifest.manifestId],
      ["Evidence", evidenceText],
    ], y, "Consolidated Evidence Index", data.client.clientName));
  }
}

export function buildConsolidatedHygieneClientPackFileName(data: ConsolidatedHygieneClientPackData): string {
  const period = periodText(data.period).replace(/\s+to\s+/i, "_to_");
  return "Torque-Empire_Hygiene_" + slug(data.client.clientName) + "_Consolidated-Client-Pack_" + slug(period) + ".pdf";
}

export async function generateConsolidatedHygieneClientPackPdf(
  data: ConsolidatedHygieneClientPackData,
  certificateAttachments: ConsolidatedCertificateAttachment[] = [],
): Promise<Uint8Array> {
  assertClientFacingHygienePdfContent([
    data.client.clientName,
    ...data.entries.flatMap((entry) => [
      entry.collection.collectionId,
      entry.manifest.manifestId,
      entry.site.siteName,
      entry.manifest.wasteType,
    ]),
  ]);
  const kit = await createKit();
  kit.document.setTitle("Torque Empire Hygiene Consolidated Client Pack");
  kit.document.setSubject("Consolidated Hygiene client manifest pack generated by TEOS on behalf of Torque Empire (Pty) Ltd");

  const cover = kit.document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawConsolidatedCover(cover, kit, data);
  drawConsolidatedRegister(kit, data);

  for (const entry of data.entries) {
    const page = addPage(kit, "Waste Manifest", entry.manifest.manifestId);
    drawManifestBody(kit, page, {
      manifest: entry.manifest,
      collection: entry.collection,
      client: data.client,
      site: entry.site,
      disposalEvidence: [],
      generatedAt: data.generatedAt,
    });
  }

  drawConsolidatedEvidenceIndex(kit, data, certificateAttachments);
  for (const attachment of certificateAttachments) {
    const sourceDocument = await PDFDocument.load(attachment.bytes);
    const pages = await kit.document.copyPages(sourceDocument, sourceDocument.getPageIndices());
    pages.forEach((page) => kit.document.addPage(page));
  }

  return kit.document.save();
}

export async function generateHygieneClientPackPdf(data: HygienePdfDocumentData, certificatePdfBytes?: Uint8Array | null): Promise<Uint8Array> {
  const kit = await createKit();
  const cover = kit.document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawClientPackCover(cover, kit, data);

  const manifestPage = addPage(kit, "Waste Manifest", data.manifest.manifestId);
  drawManifestBody(kit, manifestPage, data);

  const certificateIncluded = Boolean(certificatePdfBytes?.byteLength);
  if (certificatePdfBytes?.byteLength) {
    const certificateDocument = await PDFDocument.load(certificatePdfBytes);
    const certificatePages = await kit.document.copyPages(certificateDocument, certificateDocument.getPageIndices());
    certificatePages.forEach((page) => kit.document.addPage(page));
  }

  const index = addPage(kit, "Compliance Index", data.manifest.manifestId);
  drawComplianceIndex(index, kit, data, certificateIncluded);
  return kit.document.save();
}
