import type {
  HygieneBinAsset,
  HygieneClient,
  HygieneCollection,
  HygieneComplianceDocument,
  HygieneDriverLog,
  HygieneReport,
  HygieneSite,
  HygieneVehicleInspection,
  HygieneManifest,
  HygieneWorkflowStep,
} from "@/types/hygiene";

export const HYGIENE_GENERATOR_REGISTRATION = "GPG-15-793";
export const HYGIENE_TRANSPORT_REGISTRATION = "GPT-15-858";
export const HYGIENE_COMPANY_REGISTRATION = "2024/105084/07";

const now = "2026-06-20T00:00:00+02:00";

const completedWorkflowSteps: HygieneWorkflowStep[] = [
  "Start collection",
  "Confirm site arrival",
  "Capture before-service photo",
  "Record bin count",
  "Confirm liner removal",
  "Confirm bag sealed",
  "Upload evidence photos",
  "Confirm transport container loaded",
  "Capture client signature",
  "Complete collection",
  "Generate/attach manifest",
].map((label, index) => ({
  stepId: `step-${String(index + 1).padStart(2, "0")}`,
  label,
  status: "Completed",
}));

const pendingWorkflowSteps: HygieneWorkflowStep[] = completedWorkflowSteps.map((step) => ({
  ...step,
  status: "Pending",
}));

export const cbavoClient: HygieneClient = {
  clientId: "TE-CLI-0001",
  clientName: "CBAVO Services",
  clientType: "Hygiene Client",
  companyRegistration: HYGIENE_COMPANY_REGISTRATION,
  primaryContactName: "CBAVO Site Coordinator",
  primaryContactPhone: "Not captured",
  primaryContactEmail: "operations@cbavo.example",
  billingContact: "CBAVO Accounts",
  contractStartDate: "2026-06-18",
  contractEndDate: "2026-07-18",
  serviceFrequency: "Weekly",
  collectionDay: "Friday",
  collectionWindow: "After 13:00",
  paymentStatus: "Paid",
  status: "Active",
  monthlyRevenue: 0,
  createdAt: now,
  updatedAt: now,
};

export const cbavoSites: HygieneSite[] = [
  {
    siteId: "TE-SIT-0001",
    clientId: "TE-CLI-0001",
    siteName: "Florida Campus",
    address: "40/42 Goldman Street, Florida",
    suburb: "Florida",
    city: "Roodepoort",
    contactPerson: "CBAVO Site Coordinator",
    contactPhone: "Not captured",
    binCount: 4,
    binSize: "12L",
    serviceFrequency: "Weekly",
    accessNotes: "Friday collection after 13:00.",
    lastServiceDate: "2026-06-19",
    nextServiceDate: "2026-06-26",
    status: "Active",
  },
  {
    siteId: "TE-SIT-0002",
    clientId: "TE-CLI-0001",
    siteName: "Ontdekkers Campus",
    address: "Ontdekkers, Roodepoort",
    suburb: "Ontdekkers",
    city: "Roodepoort",
    contactPerson: "CBAVO Site Coordinator",
    contactPhone: "Not captured",
    binCount: 5,
    binSize: "12L",
    serviceFrequency: "Weekly",
    accessNotes: "Friday collection after 13:00.",
    lastServiceDate: "2026-06-19",
    nextServiceDate: "2026-06-26",
    status: "Active",
  },
];

export const cbavoBinAssets: HygieneBinAsset[] = Array.from({ length: 9 }, (_, index) => {
  const sequence = index + 1;
  const siteId = sequence <= 4 ? "TE-SIT-0001" : "TE-SIT-0002";
  const locationSequence = siteId === "TE-SIT-0001" ? sequence : sequence - 4;

  return {
    assetId: `TE-BIN-2026-${String(sequence).padStart(4, "0")}`,
    clientId: "TE-CLI-0001",
    siteId,
    binSize: "12L",
    binType: "Sanitary hygiene bin",
    locationDescription: `${siteId === "TE-SIT-0001" ? "Florida" : "Ontdekkers"} service point ${locationSequence}`,
    status: "Active",
    installDate: "2026-06-18",
    lastServiceDate: "2026-06-19",
    nextServiceDate: "2026-06-26",
    condition: "Serviceable",
    notes: "Assigned to CBAVO weekly hygiene service.",
  };
});

export const cbavoCollections: HygieneCollection[] = [
  {
    collectionId: "TE-COL-2026-0001",
    clientId: "TE-CLI-0001",
    siteId: "TE-SIT-0001",
    scheduledDate: "2026-06-19",
    scheduledTimeWindow: "After 13:00",
    assignedDriver: "C. Karanie",
    vehicleRegistration: "JG 71 RS GP",
    vehicleName: "Nissan NP200",
    status: "Completed",
    arrivalTime: "2026-06-19T13:05:00+02:00",
    departureTime: "2026-06-19T14:10:00+02:00",
    completedAt: "2026-06-19T14:10:00+02:00",
    manifestId: "TE-WM-2026-0001",
    evidencePhotoIds: [],
    clientSignatureStatus: "Pending signature capture",
    notes: "First completed CBAVO hygiene collection. Florida and Ontdekkers manifests attached.",
    workflowSteps: completedWorkflowSteps,
  },
  {
    collectionId: "TE-COL-2026-0002",
    clientId: "TE-CLI-0001",
    siteId: "TE-SIT-0001",
    scheduledDate: "2026-06-26",
    scheduledTimeWindow: "After 13:00",
    assignedDriver: "C. Karanie",
    vehicleRegistration: "JG 71 RS GP",
    vehicleName: "Nissan NP200",
    status: "Scheduled",
    arrivalTime: null,
    departureTime: null,
    completedAt: null,
    manifestId: "Pending",
    evidencePhotoIds: [],
    clientSignatureStatus: "Pending",
    notes: "Weekly Friday collection after 13:00.",
    workflowSteps: pendingWorkflowSteps,
  },
];

export const cbavoManifests: HygieneManifest[] = [
  {
    manifestId: "TE-WM-2026-0001",
    collectionId: "TE-COL-2026-0001",
    clientId: "TE-CLI-0001",
    siteId: "TE-SIT-0001",
    generatorRegistration: HYGIENE_GENERATOR_REGISTRATION,
    transportRegistration: HYGIENE_TRANSPORT_REGISTRATION,
    wasteClassification: "HW19",
    wasteType: "Sanitary/Feminine Hygiene Waste",
    quantity: 4,
    unit: "12L bins",
    collectionDate: "2026-06-19",
    collectedBy: "C. Karanie",
    vehicleRegistration: "JG 71 RS GP",
    disposalFacility: "Pending disposal facility confirmation",
    disposalDate: null,
    disposalCertificateNo: "Pending",
    status: "Disposal Pending",
    createdAt: now,
    updatedAt: now,
  },
  {
    manifestId: "TE-WM-2026-0002",
    collectionId: "TE-COL-2026-0001",
    clientId: "TE-CLI-0001",
    siteId: "TE-SIT-0002",
    generatorRegistration: HYGIENE_GENERATOR_REGISTRATION,
    transportRegistration: HYGIENE_TRANSPORT_REGISTRATION,
    wasteClassification: "HW19",
    wasteType: "Sanitary/Feminine Hygiene Waste",
    quantity: 5,
    unit: "12L bins",
    collectionDate: "2026-06-19",
    collectedBy: "C. Karanie",
    vehicleRegistration: "JG 71 RS GP",
    disposalFacility: "Pending disposal facility confirmation",
    disposalDate: null,
    disposalCertificateNo: "Pending",
    status: "Disposal Pending",
    createdAt: now,
    updatedAt: now,
  },
];

export const cbavoVehicleInspections: HygieneVehicleInspection[] = [
  {
    inspectionId: "TE-VI-2026-0001",
    date: "2026-06-19",
    vehicleRegistration: "JG 71 RS GP",
    vehicleName: "Nissan NP200",
    driver: "C. Karanie",
    odometerStart: null,
    odometerEnd: null,
    fuelStatus: "R200 Diesel",
    roadworthyStatus: "Roadworthy",
    ppeAvailable: true,
    spillKitAvailable: true,
    wasteContainerSecured: true,
    comments: "First CBAVO hygiene collection vehicle inspection passed.",
    status: "Passed",
  },
];

export const cbavoDriverLogs: HygieneDriverLog[] = [
  {
    driverLogId: "TE-DL-2026-0001",
    date: "2026-06-19",
    driverName: "C. Karanie",
    vehicleRegistration: "JG 71 RS GP",
    startKm: null,
    endKm: null,
    fuel: "R200 Diesel",
    signatureStatus: "Pending signature capture",
    linkedCollectionIds: ["TE-COL-2026-0001"],
  },
];

export const cbavoComplianceDocuments: HygieneComplianceDocument[] = [
  {
    documentId: "TE-HC-WASTE-GENERATOR",
    documentType: "Waste Generator Certificate",
    title: "Waste Generator Certificate",
    registrationNumber: HYGIENE_GENERATOR_REGISTRATION,
    status: "Compliance Green",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "Torque Empire",
    uploadedAt: now,
  },
  {
    documentId: "TE-HC-WASTE-TRANSPORTER",
    documentType: "Waste Transporter Certificate",
    title: "Waste Transporter Certificate",
    registrationNumber: HYGIENE_TRANSPORT_REGISTRATION,
    status: "Compliance Warning",
    issueDate: null,
    expiryDate: "2027-05-08",
    fileUrl: null,
    owner: "Torque Empire",
    uploadedAt: now,
  },
  {
    documentId: "TE-HC-COIDA",
    documentType: "COIDA",
    title: "COIDA",
    registrationNumber: "Pending upload",
    status: "Pending",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "Torque Empire",
    uploadedAt: null,
  },
  {
    documentId: "TE-HC-SERVICE-AGREEMENT",
    documentType: "Service Agreement",
    title: "Service Agreement",
    registrationNumber: "CBAVO Services",
    status: "Compliance Green",
    issueDate: "2026-06-18",
    expiryDate: "2026-07-18",
    fileUrl: null,
    owner: "CBAVO Services",
    uploadedAt: now,
  },
  {
    documentId: "TE-HC-SLA",
    documentType: "SLA",
    title: "SLA",
    registrationNumber: "CBAVO Weekly Friday After 13:00",
    status: "Compliance Green",
    issueDate: "2026-06-18",
    expiryDate: "2026-07-18",
    fileUrl: null,
    owner: "CBAVO Services",
    uploadedAt: now,
  },
  {
    documentId: "TE-HC-SIGNED-QUOTATION",
    documentType: "Signed Quotation",
    title: "Signed Quotation",
    registrationNumber: "CBAVO Hygiene Onboarding",
    status: "Compliance Green",
    issueDate: "2026-06-18",
    expiryDate: null,
    fileUrl: null,
    owner: "CBAVO Services",
    uploadedAt: now,
  },
  {
    documentId: "TE-HC-DISPOSAL-CERTIFICATES",
    documentType: "Disposal Certificates",
    title: "Disposal Certificates",
    registrationNumber: "Pending",
    status: "Pending",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "CBAVO Services",
    uploadedAt: null,
  },
  {
    documentId: "TE-HC-VEHICLE-LICENCE",
    documentType: "Vehicle Licence",
    title: "Vehicle Licence",
    registrationNumber: "JG 71 RS GP",
    status: "Pending",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "Torque Empire",
    uploadedAt: null,
  },
  {
    documentId: "TE-HC-DRIVER-LICENCE",
    documentType: "Driver Licence",
    title: "Driver Licence",
    registrationNumber: "C. Karanie",
    status: "Pending",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "C. Karanie",
    uploadedAt: null,
  },
  {
    documentId: "TE-HC-PUBLIC-LIABILITY",
    documentType: "Public Liability Insurance",
    title: "Public Liability Insurance",
    registrationNumber: "If available",
    status: "Pending",
    issueDate: null,
    expiryDate: null,
    fileUrl: null,
    owner: "Torque Empire",
    uploadedAt: null,
  },
];

export const cbavoReports: HygieneReport[] = [
  {
    reportId: "TE-HR-2026-06",
    period: "2026-06",
    collectionsCompleted: 1,
    sitesServiced: 2,
    totalBinsServiced: 9,
    manifestsCreated: 2,
    disposalCertificatesPending: 2,
    incidents: 0,
    evidenceCompletionPercentage: 0,
    revenueSummary: 0,
    createdAt: now,
  },
];
