"use client";

import Badge from "@/components/ui/Badge";
import Card from "@/components/ui/Card";
import type { WorkflowStep } from "@/lib/manus/types/manus.types";

function dotClass(status: WorkflowStep["status"]) {
  if (status === "completed") return "bg-emerald-500";
  if (status === "running") return "bg-sky-500";
  if (status === "failed" || status === "rolled_back") return "bg-rose-500";
  if (status === "skipped") return "bg-amber-400";
  return "bg-slate-300";
}

function toneForStatus(status: WorkflowStep["status"]): "success" | "warning" | "danger" | "neutral" {
  if (status === "completed") return "success";
  if (status === "running" || status === "pending" || status === "skipped") return "warning";
  if (status === "failed" || status === "rolled_back") return "danger";
  return "neutral";
}

export function WorkflowTimeline(props: {
  steps: WorkflowStep[];
  workflowDurationMs?: number;
  readinessClassification?: string;
  operationalRecommendations?: string[];
}) {
  return (
    <Card className="rounded-[28px] border border-slate-200 bg-[linear-gradient(180deg,#ffffff_0%,#f8fbff_100%)] p-5 shadow-sm">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Workflow Timeline</p>
          <h3 className="mt-2 text-xl font-semibold text-slate-900">Operational Execution Chain</h3>
          <p className="mt-1 text-sm text-slate-600">Controlled Manus orchestration with full dry-run visibility.</p>
        </div>
        <div className="flex flex-wrap gap-2">
          {props.readinessClassification ? <Badge tone="info">{props.readinessClassification}</Badge> : null}
          {typeof props.workflowDurationMs === "number" ? <Badge tone="neutral">{props.workflowDurationMs}ms</Badge> : null}
        </div>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]">
        <div className="space-y-4">
          {props.steps.map((step, index) => (
            <div
              key={step.id}
              className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white px-4 py-4 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"
            >
              {index < props.steps.length - 1 ? <div className="absolute left-5 top-12 h-full w-px bg-slate-200" /> : null}
              <div className="flex gap-3">
                <div className={`mt-1 h-3 w-3 shrink-0 rounded-full ${dotClass(step.status)}`} />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                    <p className="text-sm font-semibold text-slate-900">{step.title}</p>
                    <Badge tone={toneForStatus(step.status)}>{step.status}</Badge>
                  </div>
                  <p className="mt-2 text-sm text-slate-600">
                    {step.actor ? `${step.actor} • ` : ""}
                    {typeof step.durationMs === "number" ? `${step.durationMs}ms` : "Awaiting duration"}
                    {typeof step.retries === "number" && step.retries > 0 ? ` • retries ${step.retries}` : ""}
                  </p>
                  {Array.isArray(step.warnings) && step.warnings.length > 0 ? (
                    <div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">
                      {step.warnings.join(" | ")}
                    </div>
                  ) : null}
                  {step.error ? <p className="mt-3 text-sm text-rose-700">{step.error}</p> : null}
                </div>
              </div>
            </div>
          ))}
        </div>

        <aside className="space-y-3">
          <div className="rounded-3xl border border-slate-200 bg-white px-4 py-4 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Readiness</p>
            <p className="mt-2 text-2xl font-semibold text-slate-900">{props.readinessClassification ?? "Pending"}</p>
            <p className="mt-1 text-sm text-slate-600">Operational classification generated by the scoring agent.</p>
          </div>
          <div className="rounded-3xl border border-slate-200 bg-white px-4 py-4 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Recommendations</p>
            <div className="mt-3 space-y-2">
              {(props.operationalRecommendations ?? ["Await workflow recommendations"]).map((item, index) => (
                <div key={`${item}-${index}`} className="rounded-2xl bg-slate-50 px-3 py-2 text-sm text-slate-700">
                  {item}
                </div>
              ))}
            </div>
          </div>
        </aside>
      </div>
    </Card>
  );
}

export default WorkflowTimeline;
