export const runtime = "nodejs";
import crypto from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getFirebaseStorageBucket } from "@/lib/firebase/admin";
import { assertVehicleFinanceStaffRole, AuthorizationError, requireAuthorizedUser } from "@/lib/server/authz";
import { createVehicleFinanceSupplierQuote, VehicleFinanceProcurementValidationError } from "@/lib/vehicleFinance/vehicleFinanceService";
const MAX=10*1024*1024; const TYPES=new Map([["application/pdf",".pdf"],["application/vnd.openxmlformats-officedocument.wordprocessingml.document",".docx"],["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",".xlsx"]]);
const text=(f:FormData,k:string)=>{const v=f.get(k);return typeof v==="string"?v.trim():""}; const safe=(v:string)=>v.replace(/[^a-zA-Z0-9._-]/g,"_");
export async function POST(request:NextRequest){let path:string|null=null;try{const user=await requireAuthorizedUser(request);assertVehicleFinanceStaffRole(user);const form=await request.formData();const file=form.get("file");if(!(file instanceof File))throw new VehicleFinanceProcurementValidationError("Quote file is required");const ext=file.name.toLowerCase().slice(file.name.lastIndexOf("."));if(!file.size||file.size>MAX)throw new VehicleFinanceProcurementValidationError("Quote file must be between 1 byte and 10 MiB");if(TYPES.get(file.type)!==ext)throw new VehicleFinanceProcurementValidationError("Unsupported quote file type");const supplierId=text(form,"supplierId"),procurementCaseId=text(form,"procurementCaseId");if(!supplierId||!procurementCaseId)throw new VehicleFinanceProcurementValidationError("Supplier and procurement case are required");const documentId=crypto.randomUUID();path=`vehicle-finance/procurement-cases/${procurementCaseId}/supplier-quotes/${documentId}_${safe(file.name)}`;await getFirebaseStorageBucket().file(path).save(Buffer.from(await file.arrayBuffer()),{resumable:false,metadata:{contentType:file.type,cacheControl:"private, no-store"}});const supplierQuote=await createVehicleFinanceSupplierQuote({supplierId,procurementCaseId,vehicleDescription:text(form,"vehicleDescription"),quotedAmount:text(form,"quotedAmount"),availability:text(form,"availability"),quoteDate:text(form,"quoteDate"),supplierReference:text(form,"supplierReference"),supportingDocuments:[{documentId,fileName:file.name,storagePath:path,mimeType:file.type,sizeBytes:file.size,uploadedAt:new Date().toISOString(),uploadedBy:user.uid}]},{actorId:user.uid,actorRole:user.role,actorName:user.email??user.uid});return NextResponse.json({supplierQuote},{status:201});}catch(error){if(path)await getFirebaseStorageBucket().file(path).delete({ignoreNotFound:true}).catch(()=>undefined);const status=error instanceof AuthorizationError?error.status:error instanceof VehicleFinanceProcurementValidationError?error.status:500;return NextResponse.json({error:error instanceof Error?error.message:"Supplier quote upload failed"},{status});}}
