import * as repair from "@/lib/contractors/canonicalContractorIdentityWorkspaceRepair"
type Store = Record<string, repair.JsonRecord>
const c = repair.CANONICAL_CONTRACTOR_PATH; const d = repair.CANONICAL_CSD_DOCUMENT_PATH; const u = "users/" + repair.APPROVED_USER_ID
function contractor(extra: repair.JsonRecord = {}) { return { contractorId: repair.CANONICAL_CONTRACTOR_ID, registrationNumber: repair.APPROVED_REGISTRATION_NUMBER, companyRegistrationNumber: repair.APPROVED_REGISTRATION_NUMBER, userId: repair.APPROVED_USER_ID, authUid: repair.APPROVED_USER_ID, workspaceId: null, legalName: null, registeredBusinessName: null, tradingName: null, companyName: null, businessName: null, identityResolved: null, identityStatus: null, identityResolutionStatus: null, businessIdentityEvidenceStatus: null, csdNumber: "MISREPRESENT", csdMNumber: "MISREPRESENT", mNumber: "MISREPRESENT", sarsTcsSummary: { status: "REVIEW_REQUIRED" }, readinessScore: 1, assignmentAllowed: false, ...extra } }
function csd(extra: repair.JsonRecord = {}) { return { storagePath: repair.VERIFIED_CSD_PDF_PATH, supplierNumber: repair.APPROVED_SUPPLIER_NUMBER, csdNumber: repair.APPROVED_SUPPLIER_NUMBER, registrationNumber: repair.APPROVED_REGISTRATION_NUMBER, verifiedAt: "t", verifiedBy: "u", ...extra } }
function store(extra: Store = {}): Store { return { [c]: contractor(), [d]: csd(), [u]: { workspaceId: repair.APPROVED_WORKSPACE_ID, contractorId: repair.CANONICAL_CONTRACTOR_ID }, ["deals/" + repair.CANONICAL_DEAL_ID]: { workspaceId: repair.APPROVED_WORKSPACE_ID }, ["opportunityExecutionWorkspaces/" + repair.CANONICAL_DEAL_ID]: { workspaceId: repair.APPROVED_WORKSPACE_ID }, ["contractors/" + repair.POLLUTED_CONTRACTOR_ID]: { untouched: true }, ...extra } }
function reader(s: Store) { const reads: string[] = []; return { reads, async getDocument(path: string) { reads.push(path); const data = s[path] ?? null; return { path, id: path, exists: data !== null, data } } } }
async function plan(s = store(), contractorId = repair.CANONICAL_CONTRACTOR_ID, csdPath = d) { const r = reader(s); const result = await repair.buildCanonicalContractorRepairPlan(r, { contractorId, csdDocumentPath: csdPath, dealId: repair.CANONICAL_DEAL_ID, mode: "dry-run", dryRunConfirmation: repair.DRY_RUN_CONFIRMATION }); return { result, r } }
describe("canonical contractor repair dry-run", () => {
  test("dry-run reads exact paths and makes zero writes", async () => { const { result, r } = await plan(); expect(result.status).toBe("READY_FOR_APPLY"); expect(result.productionWrites).toBe(0); expect(result.futureWriteAllowlist).toEqual([c, d]); expect(r.reads).toEqual([c, d, u, "deals/" + repair.CANONICAL_DEAL_ID, "opportunityExecutionWorkspaces/" + repair.CANONICAL_DEAL_ID]) })
  test("rejects polluted contractor, wrong CSD path, old PDF, and drift", async () => { const s = store({ [c]: contractor({ legalName: "set" }), [d]: csd({ storagePath: "old.pdf" }) }); const { result } = await plan(s, repair.POLLUTED_CONTRACTOR_ID, "bad"); const text = result.blockers.join("|"); expect(result.status).toBe("BLOCKED"); expect(text).toContain("Polluted contractor"); expect(text).toContain("Wrong CSD document path"); expect(text).toContain("verified PDF") })
  test("rejects registration user workspace and supplier mismatches", async () => { const s = store({ [c]: contractor({ registrationNumber: "bad", userId: "bad" }), [d]: csd({ supplierNumber: "MAAA0" }), [u]: { workspaceId: "bad", contractorId: "bad" } }); const { result } = await plan(s); const text = result.blockers.join("|"); expect(text).toContain("registrationNumber"); expect(text).toContain("userId"); expect(text).toContain("workspace"); expect(text).toContain("CSD supplier number") })
  test("protected categories untouched and apply writes only two records", async () => { const s = store(); const { result } = await plan(s); const changed = result.records.flatMap((record) => record.diff.map((entry) => entry.field.toLowerCase())); expect(changed.some((field) => /sars|tcs|readiness|assignment|phase|activity|note|audit/.test(field))).toBe(false); const writes: Array<{ path: string; data: unknown }> = []; const writer = { ...reader(s), doc: (path: string) => ({ path }), async runTransaction<T>(cb: (tx: repair.RepairTransaction) => Promise<T>) { return cb({ get: async (ref: { path: string }) => ({ exists: Boolean(s[ref.path]), data: () => s[ref.path] }), set: async (ref: { path: string }, data: unknown) => { writes.push({ path: ref.path, data }) } }) } }; const fs = jest.requireActual<typeof import("node:fs")>("node:fs"); fs.mkdirSync("reports/contractors", { recursive: true }); fs.writeFileSync("reports/contractors/test-backup.json", JSON.stringify(result.backup)); fs.writeFileSync("reports/contractors/test-allowlist.json", JSON.stringify(result.allowlist)); const fp = repair.materialFingerprints(result); await expect(repair.applyCanonicalContractorRepair(writer, { contractorId: repair.CANONICAL_CONTRACTOR_ID, csdDocumentPath: d, dealId: repair.CANONICAL_DEAL_ID, mode: "apply", productionConfirmation: repair.PRODUCTION_CONFIRMATION, backupPath: "reports/contractors/test-backup.json", allowlistPath: "reports/contractors/test-allowlist.json", expectedContractorFingerprint: "bad", expectedCsdFingerprint: fp.csd })).rejects.toThrow("fingerprint"); const applied = await repair.applyCanonicalContractorRepair(writer, { contractorId: repair.CANONICAL_CONTRACTOR_ID, csdDocumentPath: d, dealId: repair.CANONICAL_DEAL_ID, mode: "apply", productionConfirmation: repair.PRODUCTION_CONFIRMATION, backupPath: "reports/contractors/test-backup.json", allowlistPath: "reports/contractors/test-allowlist.json", expectedContractorFingerprint: fp.contractor, expectedCsdFingerprint: fp.csd }); expect(applied.productionWrites).toBe(2); expect(writes.map((write) => write.path)).toEqual([c, d]) })
})




