import { NextRequest } from "next/server";
const requireUser=jest.fn(), staffRole=jest.fn(), bucket=jest.fn(), createQuote=jest.fn(), getDoc=jest.fn();
class VError extends Error { constructor(message:string, public status=400){super(message)} }
class AError extends Error { constructor(message:string, public status=403){super(message)} }
jest.mock("@/lib/server/authz",()=>({requireAuthorizedUser:(r:unknown)=>requireUser(r),assertVehicleFinanceStaffRole:(u:unknown)=>staffRole(u),AuthorizationError:AError}));
jest.mock("@/lib/firebase/admin",()=>({getFirebaseStorageBucket:()=>bucket()}));
jest.mock("@/lib/vehicleFinance/vehicleFinanceService",()=>({createVehicleFinanceSupplierQuote:(...a:unknown[])=>createQuote(...a),getVehicleFinanceSupplierQuoteDocument:(...a:unknown[])=>getDoc(...a),VehicleFinanceProcurementValidationError:VError}));
import { POST } from "@/app/api/vehicle-finance/supplier-quotes/upload/route";
import { GET } from "@/app/api/vehicle-finance/supplier-quotes/[supplierQuoteId]/documents/[documentId]/route";
const user={uid:"staff",role:"staff",email:"staff@test"}; const file=(name="quote.pdf",type="application/pdf",size=3)=>new File([new Uint8Array(size)],name,{type});
function request(f:File){const form=new FormData();form.set("supplierId","supplier-1");form.set("procurementCaseId","case-1");form.set("vehicleDescription","Vehicle");form.set("quotedAmount","100");form.set("availability","In stock");form.set("quoteDate","2026-01-01");form.set("file",f);return new NextRequest("http://test/api",{method:"POST",body:form})}
describe("vehicle finance supplier quote private upload/download",()=>{let save:jest.Mock,del:jest.Mock,download:jest.Mock;beforeEach(()=>{jest.clearAllMocks();requireUser.mockResolvedValue(user);staffRole.mockImplementation(()=>undefined);save=jest.fn().mockResolvedValue(undefined);del=jest.fn().mockResolvedValue(undefined);download=jest.fn().mockResolvedValue([Buffer.from("private")]);bucket.mockReturnValue({file:jest.fn(()=>({save,delete:del,download}))});createQuote.mockResolvedValue({supplierId:"supplier-1",procurementCaseId:"case-1",supportingDocuments:[]});getDoc.mockResolvedValue({document:{storagePath:"vehicle-finance/procurement-cases/case-1/supplier-quotes/a_quote.pdf",fileName:"quote.pdf",mimeType:"application/pdf"}})});
it("uploads an authorized internal quote with canonical linkage and private metadata",async()=>{const r=await POST(request(file()));expect(r.status).toBe(201);expect(createQuote).toHaveBeenCalledWith(expect.objectContaining({supplierId:"supplier-1",procurementCaseId:"case-1",supportingDocuments:[expect.objectContaining({fileName:"quote.pdf",mimeType:"application/pdf",sizeBytes:3,storagePath:expect.stringContaining("vehicle-finance/procurement-cases/case-1")})]}),expect.anything());expect(save).toHaveBeenCalled()});
it("rejects unauthorized and partner roles",async()=>{staffRole.mockImplementation(()=>{throw new AError("unauthorized")});expect((await POST(request(file()))).status).toBe(403)});
it("rejects a vehicleFinancePartner upload",async()=>{requireUser.mockResolvedValue({uid:"partner",role:"vehicleFinancePartner"});staffRole.mockImplementation(()=>{throw new AError("unauthorized")});expect((await POST(request(file()))).status).toBe(403)});
it("rejects invalid supplier and procurement case",async()=>{createQuote.mockRejectedValueOnce(new VError("Supplier not found",409));expect((await POST(request(file()))).status).toBe(409);createQuote.mockRejectedValueOnce(new VError("Procurement case not found",409));expect((await POST(request(file()))).status).toBe(409)});
it("rejects unsupported and oversize files",async()=>{expect((await POST(request(file("x.exe","application/octet-stream")))).status).toBe(400);expect((await POST(request(file("x.pdf","application/pdf",10*1024*1024+1)))).status).toBe(400)});
it("cleans storage when canonical creation fails",async()=>{createQuote.mockRejectedValue(new VError("Supplier not found",409));expect((await POST(request(file()))).status).toBe(409);expect(del).toHaveBeenCalled()});
it("streams private document only for authorized internal users",async()=>{const r=await GET(new NextRequest("http://test"),{params:Promise.resolve({supplierQuoteId:"q",documentId:"d"})});expect(r.status).toBe(200);expect(await r.text()).toBe("private");expect(r.headers.get("cache-control")).toBe("private, no-store")});
it("denies partner download",async()=>{requireUser.mockResolvedValue({uid:"partner",role:"vehicleFinancePartner"});staffRole.mockImplementation(()=>{throw new AError("unauthorized")});expect((await GET(new NextRequest("http://test"),{params:Promise.resolve({supplierQuoteId:"q",documentId:"d"})})).status).toBe(403)});
it("denies download and fails closed for invalid linkage",async()=>{staffRole.mockImplementation(()=>{throw new AError("unauthorized")});expect((await GET(new NextRequest("http://test"),{params:Promise.resolve({supplierQuoteId:"q",documentId:"d"})})).status).toBe(403);staffRole.mockImplementation(()=>undefined);getDoc.mockRejectedValue(new VError("Quote document is unavailable",404));expect((await GET(new NextRequest("http://test"),{params:Promise.resolve({supplierQuoteId:"q",documentId:"d"})})).status).toBe(404)});});



