export type ContractorTier = "basic" | "bronze" | "silver" | "gold" | "platinum";

export interface Contractor {
  id: string;
  name?: string | null;
  companyName?: string | null;
  companyRegistrationNumber?: string | null;
  registrationNumber?: string | null;
  bbbeeLevel?: string | null;
  taxPin?: string | null;
  taxNumber?: string | null;
  taxReferenceNumber?: string | null;
  taxpayerName?: string | null;
  taxClearanceExpiry?: number | null;
  coidaRegistrationNumber?: string | null;
  coidaExpiry?: number | null;
  bankVerified?: boolean | null;
  bankName?: string | null;
  bankAccountHolder?: string | null;
  bankAccountNumber?: string | null;
  bankBranchCode?: string | null;
  contactPerson?: string | null;
  email?: string | null;
  phone?: string | null;
  status?: string | null;
  tier?: ContractorTier | null;
  submissionsUsed?: number | null;
  submissionsLimit?: number | null;
  readinessScore?: number | null;
  complianceConfidence?: number | null;
  readinessConfidence?: number | null;
  operationalSubmissionConfidence?: number | null;
  riskGrade?: "LOW RISK" | "MODERATE RISK" | "REVIEW REQUIRED" | "HIGH RISK" | null;
  explainableSummary?: string | null;
  blockedReasons?: string[] | null;
  reviewRecommendations?: string[] | null;
  docsMissing?: number | null;
  tenderLockStatus?: "READY" | "RISK" | "BLOCKED" | null;
  isTenderLocked?: boolean | null;
  createdAt?: number | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  lastDocumentUpdateAt?: string | null;
  lastDocumentType?: string | null;
  lastDocumentStoragePath?: string | null;
}
