import Image from 'next/image';
import Link from 'next/link';

import { TORQUE_EMPIRE_BRAND_ASSETS } from '@/lib/branding/identity';
import { getCorporateMailto, TORQUE_EMPIRE_COMPANY_PROFILE } from '@/lib/corporate/companyProfile';
import { automotiveMedia, automotiveSourcingJourney, complianceCredentials, coreValues, corporateDivisions, corporateNavItems, nuwkemPositioning, serviceDetails, teosOutcomes, teosPlatformSummary, whyTorqueEmpire, type CorporateDivision, type ServiceDetail } from '@/lib/corporate/websiteContent';
import QuoteRequestForm from '@/components/corporate/QuoteRequestForm';

const profile = TORQUE_EMPIRE_COMPANY_PROFILE;
const buttonPrimary = 'inline-flex min-h-11 items-center justify-center rounded-md bg-[#0b2f57] px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-[#07111f] focus:outline-none focus:ring-2 focus:ring-[#0b2f57]/30';
const buttonLight = 'inline-flex min-h-11 items-center justify-center rounded-md bg-white px-5 py-3 text-sm font-bold text-[#07111f] shadow-sm transition hover:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-white/60';
const buttonOutline = 'inline-flex min-h-11 items-center justify-center rounded-md border border-white/65 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white/50';

export function CorporateShell({ children }: { children: React.ReactNode }) { return <div className='min-h-screen overflow-x-hidden bg-[#f7f4ee] text-[#07111f] antialiased'><CorporateHeader />{children}<CorporateFooter /></div>; }

export function CorporateHeader() { return (
  <header className='sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 shadow-sm backdrop-blur'>
    <div className='mx-auto flex min-h-20 w-full max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8'>
      <Link href='/' className='flex min-w-0 items-center gap-3 focus:outline-none focus:ring-2 focus:ring-[#0b2f57]/30' aria-label='Torque Empire home'><Image src={TORQUE_EMPIRE_BRAND_ASSETS.logoPrimaryPng} alt='Torque Empire' width={176} height={56} priority unoptimized className='h-12 w-auto' /></Link>
      <nav aria-label='Main navigation' className='hidden items-center gap-1 xl:flex'>{corporateNavItems.map((item) => <Link key={item.href} href={item.href} className='rounded-md px-3 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-100 hover:text-[#0b2f57] focus:outline-none focus:ring-2 focus:ring-[#0b2f57]/25'>{item.label}</Link>)}<Link href='/login' className='rounded-md px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100'>Login</Link></nav>
      <div className='hidden items-center gap-2 sm:flex'><Link href='/quote' className={buttonPrimary}>Request a Quote</Link></div>
      <details className='group relative xl:hidden'><summary className='flex min-h-11 cursor-pointer list-none items-center rounded-md border border-slate-200 px-3 py-2 text-sm font-bold text-[#0b2f57] marker:hidden'>Menu</summary><div className='absolute right-0 mt-2 grid w-[min(88vw,22rem)] gap-1 rounded-md border border-slate-200 bg-white p-3 shadow-xl'>{corporateNavItems.map((item) => <Link key={item.href} href={item.href} className='rounded-md px-3 py-3 text-sm font-bold text-slate-700 hover:bg-slate-100'>{item.label}</Link>)}<Link href='/quote' className='rounded-md bg-[#0b2f57] px-3 py-3 text-sm font-bold text-white'>Request a Quote</Link><Link href='/login' className='rounded-md px-3 py-3 text-sm font-bold text-slate-700 hover:bg-slate-100'>Secure TEOS Login</Link></div></details>
    </div>
  </header>
); }

export function CorporateFooter() { return (
  <footer className='border-t border-slate-200 bg-white'>
    <div className='mx-auto grid w-full max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1.1fr_0.8fr_0.8fr_0.9fr] lg:px-8'>
      <div><Image src={TORQUE_EMPIRE_BRAND_ASSETS.logoPrimaryPng} alt='Torque Empire' width={176} height={56} unoptimized className='h-12 w-auto' /><p className='mt-4 max-w-xl text-sm leading-6 text-slate-600'>{profile.tagline} {profile.companyName} is a South African technology and professional services company.</p><Link href='/quote' className='mt-5 inline-flex rounded-md bg-[#0b2f57] px-4 py-2.5 text-sm font-bold text-white'>Request a Quote</Link></div>
      <FooterLinks title='Company' links={[...corporateNavItems, { label: 'Quote', href: '/quote' }]} />
      <FooterLinks title='Services' links={[...corporateDivisions.map((division) => ({ label: division.shortName, href: division.href })), { label: 'TEOS Platform', href: '/teos-platform' }]} />
      <div><h2 className='text-sm font-bold uppercase tracking-[0.18em] text-[#0b2f57]'>Contact information</h2><p className='mt-4 text-sm leading-6 text-slate-600'>Government, enterprise, supplier, and partnership enquiries are welcome.</p><a href={getCorporateMailto('info')} className='mt-3 block text-sm font-bold text-[#0b2f57] underline underline-offset-4'>{profile.businessEmails.info}</a><a href={'tel:' + profile.telephone.replace(/\\s/g, '')} className='mt-3 block text-sm font-bold text-slate-700'>{profile.telephone}</a><p className='mt-2 text-sm text-slate-600'>Service area: {profile.serviceArea}</p><div className='mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500'><Link href='/privacy-policy'>Privacy Policy</Link><Link href='/terms-of-use'>Terms of Use</Link></div></div>
    </div>
    <div className='border-t border-slate-200 px-4 py-4 text-center text-xs text-slate-500'>Copyright (c) 2026 Torque Empire (Pty) Ltd. All rights reserved.</div>
  </footer>
); }

function FooterLinks({ title, links }: { title: string; links: Array<{ label: string; href: string }> }) { return <div><h2 className='text-sm font-bold uppercase tracking-[0.18em] text-[#0b2f57]'>{title}</h2><div className='mt-4 grid gap-2'>{links.map((item) => <Link key={item.href + item.label} href={item.href} className='text-sm font-medium text-slate-600 hover:text-[#0b2f57]'>{item.label}</Link>)}</div></div>; }

export function HomePage() { return <CorporateShell><main>
  <section className='relative isolate min-h-[calc(100svh-5rem)] overflow-hidden bg-[#07111f] text-white'><video autoPlay muted loop playsInline poster='/corporate/logo/torque-empire-primary.png' className='absolute inset-0 h-full w-full object-cover'><source src='/login/hero.mp4' type='video/mp4' /></video><div className='absolute inset-0 bg-[#07111f]/78' /><div className='relative mx-auto flex min-h-[calc(100svh-5rem)] w-full max-w-7xl flex-col justify-center px-4 py-20 sm:px-6 lg:px-8'><p className='text-sm font-bold uppercase tracking-[0.24em] text-blue-100'>Torque Empire (Pty) Ltd</p><h1 className='mt-5 max-w-5xl text-4xl font-extrabold leading-tight tracking-normal sm:text-6xl'>Four Divisions. One Vision. Total Excellence.</h1><p className='mt-6 max-w-3xl text-lg leading-8 text-slate-200'>Torque Empire is a South African business built around procurement, hygiene and waste management, telecommunications, and automotive support. TEOS strengthens operating visibility behind secure access without becoming another public division.</p><div className='mt-8 flex flex-wrap gap-3'><Link href='/quote' className={buttonLight}>Request a Quote</Link><Link href='/services' className={buttonOutline}>Explore Our Services</Link></div></div></section>
  <Section eyebrow='Company' title='Four divisions, one integrated operating vision.'><p className='max-w-4xl text-lg leading-8 text-slate-700'>Torque Empire combines local service delivery with structured compliance, clear communication, and technology-enabled growth. The public website introduces the company; the secure TEOS dashboard remains separate for authorised operational work.</p></Section>
  <DivisionGrid />
  <Section eyebrow='Why Torque Empire' title='Built for practical delivery and formal stakeholder environments.'><CardGrid items={whyTorqueEmpire} /></Section>
  <ComplianceSection />
  <FeaturedService division={corporateDivisions[0]} detail={serviceDetails.procurement} />
  <FeaturedService division={corporateDivisions[1]} detail={serviceDetails.hygiene} reverse />
  <TeosPreview />
  <CtaBand />
</main></CorporateShell>; }

export function AboutPage() { return <CorporateShell><main><PageHero eyebrow='About Torque Empire' title='A South African company building reliable services and structured business technology.' copy='Torque Empire connects practical service delivery with a disciplined operating model that supports procurement, hygiene, telecommunications, automotive support, and secure TEOS workflows.' /><Section eyebrow='Company overview' title='Built for growth, participation, and accountable delivery.'><div className='grid gap-6 lg:grid-cols-2'><TextPanel title='Founding vision' copy='Torque Empire is being built as a multi-division company that can serve clients, develop contractor capability, and use technology to make operational work more visible.' /><TextPanel title='Local economic participation' copy='The business model supports supplier coordination, contractor development, employment opportunity, and professional participation in South African service markets.' /></div></Section><Section eyebrow='Mission, vision, values' title='The standards behind the company.'><div className='grid gap-4 md:grid-cols-2 lg:grid-cols-4'>{coreValues.map((value) => <TextPanel key={value.title} title={value.title} copy={value.copy} />)}</div></Section><DivisionGrid compact /><TeosPreview /></main></CorporateShell>; }

export function ServicesPage() { return <CorporateShell><main><PageHero eyebrow='Services' title='Focused service lines backed by one operating vision.' copy='Each public service page explains what Torque Empire can present today while keeping the secure TEOS application separate from public marketing.' /><DivisionGrid /><Section eyebrow='Technology platform' title='TEOS supports operations without becoming a fifth operating division.'><TextPanel title={teosPlatformSummary.title} copy={teosPlatformSummary.summary} href={teosPlatformSummary.href} linkLabel='Explore TEOS' /></Section></main></CorporateShell>; }

export function ServicePage({ division, detail, children }: { division: CorporateDivision; detail: ServiceDetail; children?: React.ReactNode }) { return <CorporateShell><main><PageHero eyebrow={detail.eyebrow} title={detail.title} copy={detail.description} actions={<><Link href='/quote' className={buttonLight}>{detail.primaryCta}</Link><Link href='/contact' className={buttonOutline}>Contact Torque Empire</Link></>} /><section className='bg-white'><div className='mx-auto grid w-full max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[0.9fr_1.1fr] lg:px-8'><MediaPanel division={division} /><div><h2 className='text-3xl font-extrabold tracking-normal text-[#07111f]'>{division.name}</h2><p className='mt-4 leading-7 text-slate-700'>{division.mission}</p><ul className='mt-6 grid gap-3 sm:grid-cols-2'>{detail.highlights.map((item) => <li key={item} className='rounded-md border border-slate-200 bg-slate-50 p-3 text-sm font-semibold text-slate-700'>{item}</li>)}</ul></div></div></section><Section eyebrow='How we support the work' title='A clear route from request to recordkeeping.'><NumberedGrid items={detail.process} /></Section><Section eyebrow='Governance' title='Public-safe capability statements.'><CardGrid items={detail.proofPoints.map((copy) => ({ title: 'Controlled claim', copy }))} /></Section>{children}<CtaBand title={'Ready to discuss ' + division.shortName + '?'} copy='Use the quote page to prepare a structured email request or contact Torque Empire directly.' /></main></CorporateShell>; }

export function TeosPage() { return <CorporateShell><main><PageHero eyebrow='TEOS platform' title='Secure business technology for governed operations.' copy='TEOS supports governance, contractor management, document readiness, procurement workflows, hygiene operations, audit trails, and reporting inside the authenticated application.' /><Section eyebrow='Secure application boundary' title='Public website outside, operational dashboard inside.'><CardGrid items={teosOutcomes.map((copy) => ({ title: 'TEOS supports', copy }))} /><p className='mt-8 rounded-md border border-slate-200 bg-white p-5 text-sm font-semibold leading-6 text-slate-700'>The public website does not expose dashboard content. Authorised users access TEOS through the secure login and protected dashboard routes.</p></Section><CtaBand title='Talk about TEOS-enabled operations.' copy='Start with the process that needs visibility, then scale under controlled access.' /></main></CorporateShell>; }

export function WhyPage() { return <CorporateShell><main><PageHero eyebrow='Why Torque Empire' title='A partner for organisations that value preparation, governance, and delivery.' copy='Torque Empire combines local operational understanding, compliance discipline, digital workflow capability, clear communication, and scalable supplier coordination.' /><Section eyebrow='Selection factors' title='The case for Torque Empire.'><CardGrid items={whyTorqueEmpire} /></Section><ComplianceSection /></main></CorporateShell>; }

export function ContactPage() { return <CorporateShell><main><PageHero eyebrow='Contact' title='Start a focused conversation with Torque Empire.' copy='Contact Torque Empire for service enquiries, supplier conversations, partnerships, and quote requests.' actions={<><Link href='/quote' className={buttonLight}>Request a Quote</Link><a href={getCorporateMailto('info', 'Corporate enquiry')} className={buttonOutline}>Email Torque Empire</a></>} /><Section eyebrow='Contact information' title='Use the right channel for the right conversation.'><div className='grid gap-6 lg:grid-cols-2'><div className='rounded-md border border-slate-200 bg-white p-6 shadow-sm'><h2 className='text-xl font-extrabold text-[#07111f]'>Corporate enquiries</h2><dl className='mt-5 grid gap-4 text-sm text-slate-700'><Info label='Email'><a className='text-[#0b2f57] underline underline-offset-4' href={getCorporateMailto('info')}>{profile.businessEmails.info}</a></Info><Info label='Telephone'><a href={'tel:' + profile.telephone.replace(/\\s/g, '')}>{profile.telephone}</a></Info><Info label='Company'>{profile.companyName}</Info><Info label='Service area'>{profile.serviceArea}</Info></dl></div><div className='rounded-md border border-slate-200 bg-slate-50 p-6'><h2 className='text-xl font-extrabold text-[#07111f]'>Division options</h2><div className='mt-5 grid gap-2'>{corporateDivisions.map((division) => <Link key={division.href} href={division.href} className='rounded-md border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-[#0b2f57]'>{division.name}</Link>)}</div></div></div></Section></main></CorporateShell>; }

export function QuotePage() { return <CorporateShell><main><PageHero eyebrow='Request a quote' title='Prepare a structured email request for Torque Empire.' copy='This Phase 1 quote interface validates your details and opens your email app. It does not submit to a server or create a TEOS record.' /><Section eyebrow='Quote details' title='Tell us what service you need.'><QuoteRequestForm /></Section></main></CorporateShell>; }

export function PrivacyPolicyPage() { return <CorporateShell><main><PageHero eyebrow='Privacy Policy' title='Website privacy information for public enquiries.' copy='This starter policy explains how public website enquiry information may be handled. It is practical website guidance and is not presented as formal legal advice.' /><PolicySections sections={[['Information you provide', 'You may choose to provide your name, company, email, phone, location, service need, scope, preferred date, and message when preparing an enquiry.'], ['Quote form behavior', 'The Phase 1 quote form opens your email application with a prepared message. It does not automatically create a TEOS account, CRM deal, Firebase record, or dashboard record.'], ['Cookies and analytics', 'The website may use standard technical cookies or hosting diagnostics where enabled by the deployment environment. No additional analytics claim is made here.'], ['External links', 'Links to email, telephone, suppliers, or partner material may open external applications or websites.'], ['Contact', 'Privacy questions about public website enquiries can be sent to ' + profile.businessEmails.info + '.']]} /></main></CorporateShell>; }

export function TermsPage() { return <CorporateShell><main><PageHero eyebrow='Terms of Use' title='Website terms for public information and enquiries.' copy='These starter terms describe public website use and service enquiry boundaries. They are not presented as formal legal advice.' /><PolicySections sections={[['Informational use', 'Website content is provided for general information about Torque Empire services and capabilities.'], ['No tender award guarantee', 'Procurement and tender support can improve readiness and administration, but Torque Empire does not guarantee tender awards.'], ['Quotes and availability', 'Prices, timelines, service availability, and scope are subject to written confirmation by Torque Empire.'], ['Intellectual property', 'Torque Empire names, branding, public website content, and public assets remain protected by applicable rights.'], ['External links', 'External sites and email applications are outside Torque Empire website control.'], ['Limitations', 'Use the website responsibly and verify service details directly before relying on any public-facing summary.']]} /></main></CorporateShell>; }

function PageHero({ eyebrow, title, copy, actions }: { eyebrow: string; title: string; copy: string; actions?: React.ReactNode }) { return <section className='bg-[#07111f] text-white'><div className='mx-auto w-full max-w-7xl px-4 py-16 sm:px-6 lg:px-8'><p className='text-sm font-bold uppercase tracking-[0.24em] text-blue-100'>{eyebrow}</p><h1 className='mt-5 max-w-5xl text-4xl font-extrabold leading-tight tracking-normal sm:text-5xl'>{title}</h1><p className='mt-6 max-w-3xl text-lg leading-8 text-slate-200'>{copy}</p>{actions ? <div className='mt-8 flex flex-wrap gap-3'>{actions}</div> : null}</div></section>; }
function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className='bg-[#f7f4ee]'><div className='mx-auto w-full max-w-7xl px-4 py-16 sm:px-6 lg:px-8'><p className='text-sm font-bold uppercase tracking-[0.22em] text-[#0b2f57]'>{eyebrow}</p><h2 className='mt-4 max-w-4xl text-3xl font-extrabold tracking-normal text-[#07111f] sm:text-4xl'>{title}</h2><div className='mt-8'>{children}</div></div></section>; }
function TextPanel({ title, copy, href, linkLabel }: { title: string; copy: string; href?: string; linkLabel?: string }) { return <article className='rounded-md border border-slate-200 bg-white p-6 shadow-sm'><h3 className='text-lg font-extrabold text-[#07111f]'>{title}</h3><p className='mt-3 text-sm leading-6 text-slate-600'>{copy}</p>{href ? <Link href={href} className='mt-5 inline-flex text-sm font-bold text-[#0b2f57] underline underline-offset-4'>{linkLabel ?? 'Learn more'}</Link> : null}</article>; }
function CardGrid({ items }: { items: Array<{ title: string; copy: string } | string> }) { return <div className='grid gap-4 md:grid-cols-2 lg:grid-cols-3'>{items.map((item) => typeof item === 'string' ? <TextPanel key={item} title={item} copy='This supports clearer execution, accountability, and professional engagement.' /> : <TextPanel key={item.title} title={item.title} copy={item.copy} />)}</div>; }

function DivisionGrid({ compact = false }: { compact?: boolean }) { return <Section eyebrow="Service divisions" title="Operating divisions clients can engage directly."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{corporateDivisions.map((division) => <article key={division.slug} className="group relative overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm transition duration-200 hover:-translate-y-1 hover:border-[#0b2f57]/30 hover:shadow-xl focus-within:-translate-y-1 focus-within:border-[#0b2f57]/40 motion-reduce:transition-none motion-reduce:hover:translate-y-0"><MediaPanel division={division} compact /><div className="p-5"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#0b2f57]">{division.visualTag}</p><h3 className="mt-3 text-xl font-extrabold text-[#07111f]">{division.shortName}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{compact ? division.value : division.summary}</p><Link href={division.href} className="mt-5 inline-flex min-h-10 items-center rounded-md border border-[#0b2f57] px-4 py-2 text-sm font-bold text-[#0b2f57] transition hover:bg-[#0b2f57] hover:text-white focus:outline-none focus:ring-2 focus:ring-[#0b2f57]/25">{division.cta}</Link></div></article>)}</div></Section>; }
function MediaPanel({ division, compact = false }: { division: CorporateDivision; compact?: boolean }) { const minHeight = compact ? "min-h-44" : "min-h-80"; const tone = division.slug === "hygiene" ? "from-teal-950 via-teal-800 to-cyan-700" : division.slug === "telecoms" ? "from-sky-950 via-blue-900 to-cyan-800" : division.slug === "car-sales" ? "from-neutral-950 via-slate-800 to-zinc-700" : "from-[#07111f] via-[#0b2f57] to-blue-700"; if (division.imageSrc) return <div className={"relative overflow-hidden bg-slate-900 " + minHeight}><Image src={division.imageSrc} alt={division.imageLabel} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100" unoptimized /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 via-slate-950/20 to-transparent" /><div className="absolute inset-x-4 bottom-4 rounded-md border border-white/20 bg-white/10 p-3 text-white shadow-lg backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-100">{division.visualTag}</p><p className="mt-1 text-sm font-bold">{division.imageLabel}</p></div></div>; return <div role="img" aria-label={division.imageLabel} className={"relative overflow-hidden bg-gradient-to-br " + tone + " " + minHeight}><div className="absolute inset-0 opacity-35 [background-image:linear-gradient(120deg,rgba(255,255,255,0.2)_1px,transparent_1px),linear-gradient(0deg,rgba(255,255,255,0.1)_1px,transparent_1px)] [background-size:36px_36px]" /><div className="absolute inset-6 rounded-lg border border-white/20 bg-white/10 shadow-2xl backdrop-blur-sm" /><div className="absolute inset-x-5 bottom-5 text-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-100">{division.visualTag}</p><p className="mt-2 text-base font-extrabold leading-6">{division.imageLabel}</p></div></div>; }
function ComplianceSection() { return <Section eyebrow='Compliance and credentials' title='Public-safe compliance positioning.'><CardGrid items={complianceCredentials} /><p className='mt-6 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm font-semibold leading-6 text-amber-950'>This page summarises compliance positioning only. It does not publish certificate identifiers, tax numbers, personal details, private QR codes, expiry dates, or contractor evidence.</p></Section>; }
function FeaturedService({ division, detail, reverse = false }: { division: CorporateDivision; detail: ServiceDetail; reverse?: boolean }) { return <section className='bg-white'><div className={'mx-auto grid w-full max-w-7xl gap-0 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8 ' + (reverse ? 'lg:[&>*:first-child]:order-2' : '')}><MediaPanel division={division} /><div className='border border-slate-200 bg-white p-6 lg:p-8'><p className='text-sm font-bold uppercase tracking-[0.22em] text-[#0b2f57]'>{detail.eyebrow}</p><h2 className='mt-4 text-3xl font-extrabold tracking-normal text-[#07111f]'>{detail.title}</h2><p className='mt-4 leading-7 text-slate-700'>{detail.description}</p><Link href={division.href} className='mt-6 inline-flex rounded-md bg-[#0b2f57] px-5 py-3 text-sm font-bold text-white'>Learn about {division.shortName}</Link></div></div></section>; }
function TeosPreview() { return <Section eyebrow='TEOS platform preview' title='Technology support stays behind the secure application boundary.'><div className='grid gap-6 lg:grid-cols-[0.9fr_1.1fr]'><div className='relative min-h-72 overflow-hidden rounded-md bg-slate-900'><Image src='/media/teos/teos-operations-hub-hero.webp' alt='Torque Empire Operations Hub dashboard concept visual' fill sizes='(max-width: 1024px) 100vw, 45vw' className='object-cover' unoptimized /></div><div><p className='text-lg leading-8 text-slate-700'>{teosPlatformSummary.summary}</p><ul className='mt-6 grid gap-3 sm:grid-cols-2'>{teosOutcomes.map((item) => <li key={item} className='rounded-md border border-slate-200 bg-white p-3 text-sm font-semibold text-slate-700'>{item}</li>)}</ul><Link href='/teos-platform' className='mt-6 inline-flex rounded-md border border-[#0b2f57] px-5 py-3 text-sm font-bold text-[#0b2f57]'>Explore TEOS</Link></div></div></Section>; }
function NumberedGrid({ items }: { items: string[] }) { return <ol className='grid gap-4 md:grid-cols-2 lg:grid-cols-4'>{items.map((item, index) => <li key={item} className='rounded-md border border-slate-200 bg-white p-5 shadow-sm'><span className='flex h-9 w-9 items-center justify-center rounded-full bg-[#0b2f57] text-sm font-black text-white'>{index + 1}</span><p className='mt-4 text-sm font-semibold leading-6 text-slate-700'>{item}</p></li>)}</ol>; }
function CtaBand({ title = 'Ready to work with Torque Empire?', copy = 'Use the quote page for a structured request or contact us directly for service, supplier, and partnership conversations.' }: { title?: string; copy?: string }) { return <section className='bg-[#07111f] text-white'><div className='mx-auto flex w-full max-w-7xl flex-col gap-6 px-4 py-14 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8'><div><h2 className='text-3xl font-extrabold tracking-normal'>{title}</h2><p className='mt-3 max-w-2xl leading-7 text-slate-200'>{copy}</p></div><div className='flex flex-wrap gap-3'><Link href='/quote' className={buttonLight}>Request a Quote</Link><Link href='/contact' className={buttonOutline}>Contact</Link></div></div></section>; }
function Info({ label, children }: { label: string; children: React.ReactNode }) { return <div><dt className='font-bold text-slate-900'>{label}</dt><dd className='mt-1'>{children}</dd></div>; }
function PolicySections({ sections }: { sections: Array<[string, string]> }) { return <Section eyebrow='Policy details' title='Plain-language website terms.'><div className='grid gap-4'>{sections.map(([title, copy]) => <TextPanel key={title} title={title} copy={copy} />)}</div></Section>; }

export function HygieneExtraSection() { return <Section eyebrow='Hygiene product positioning' title='Public-safe hygiene supply and service context.'><div className='grid gap-6 lg:grid-cols-[1.1fr_0.9fr]'><TextPanel title='Nuwkem and Ticra positioning' copy={nuwkemPositioning} /><div className='grid gap-3 sm:grid-cols-2'><ImageCard src='/media/partners/nuwkem/nuwkem-hygiene-environment-hero.webp' alt='Nuwkem hygiene environment product showcase' /><ImageCard src='/media/hygiene/demonstration/biohazard-awareness-poster.webp' alt='Demonstration hygiene awareness poster' caption='Demonstration media, not operational proof.' /></div></div></Section>; }

export function CarSalesExtraSection() { return <><Section eyebrow="Automotive sourcing journey" title="A structured route from enquiry to handover."><ol className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{automotiveSourcingJourney.map((step, index) => <li key={step} className="relative rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#0b2f57] text-sm font-black text-white">{index + 1}</span><p className="mt-4 text-sm font-extrabold text-[#07111f]">{step}</p></li>)}</ol><p className="mt-6 max-w-3xl text-sm font-semibold leading-6 text-slate-600">Torque Empire coordinates automotive enquiries as service requests. Public media is category presentation only and does not represent owned stock, confirmed availability, pricing, or finance approval.</p></Section><Section eyebrow="Automotive media" title="Premium category presentation without dealership lock-in."><div className="flex snap-x gap-4 overflow-x-auto pb-3 motion-safe:scroll-smooth" aria-label="Automotive category media gallery">{automotiveMedia.map((item) => <figure key={item.src} className="min-w-[82%] snap-start overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm sm:min-w-[22rem] lg:min-w-[26rem]"><div className="relative h-64 overflow-hidden bg-slate-900"><Image src={item.src} alt={item.alt} fill sizes="(max-width: 768px) 82vw, 28rem" className="object-cover transition duration-500 hover:scale-105 motion-reduce:transition-none motion-reduce:hover:scale-100" unoptimized /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/60 to-transparent" /><figcaption className="absolute inset-x-4 bottom-4 rounded-md border border-white/20 bg-white/10 p-3 text-sm font-bold text-white backdrop-blur">{item.label}</figcaption></div></figure>)}</div><div className="mt-6 rounded-lg border border-slate-200 bg-white p-5 text-sm font-semibold leading-6 text-slate-700">Roar Cars references are not used as the public identity of this page. Partner or project examples should appear only when specifically authorised and clearly labelled.</div></Section></>; }
function ImageCard({ src, alt, caption }: { src: string; alt: string; caption?: string }) { return <figure className='rounded-md border border-slate-200 bg-white p-3 shadow-sm'><div className='relative h-48 overflow-hidden rounded bg-slate-100'><Image src={src} alt={alt} fill sizes='(max-width: 768px) 100vw, 33vw' className='object-cover' unoptimized /></div>{caption ? <figcaption className='mt-2 text-xs font-semibold text-slate-600'>{caption}</figcaption> : null}</figure>; }
