import fs from "node:fs";
import path from "node:path";
import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd());
type Category = "KEEP_ACTIVE" | "KEEP_REVIEW" | "ARCHIVE_TEST" | "ARCHIVE_DUPLICATE" | "ARCHIVE_STAFF_PROFILE" | "BLOCKED_BY_DEPENDENCY" | "UNKNOWN_REQUIRES_ADMIN_REVIEW";
type Confidence = "HIGH" | "MEDIUM" | "LOW";
type Raw = Record<string, unknown>;
type Dep = { collection: string; id: string; data: Raw };
type AuthHit = { uid: string; email: string | null; displayName: string | null; role: string | null; contractorId: string | null };
type Row = Raw & { firestoreDocumentId: string; businessCompanyName: string | null; recommendedClassification: Category; classificationConfidence: Confidence; evidenceReason: string; recommendedAction: string; blockingDependencies: string[]; retainRecordId: string | null; };
const REPORT_DIR = path.join(process.cwd(), "reports", "contractors");
const JSON_REPORT = path.join(REPORT_DIR, "contractor-cleanup-report.json");
const CSV_REPORT = path.join(REPORT_DIR, "contractor-cleanup-report.csv");
const MD_REPORT = path.join(REPORT_DIR, "contractor-cleanup-report.md");
const CATEGORIES: Category[] = ["KEEP_ACTIVE", "KEEP_REVIEW", "ARCHIVE_TEST", "ARCHIVE_DUPLICATE", "ARCHIVE_STAFF_PROFILE", "BLOCKED_BY_DEPENDENCY", "UNKNOWN_REQUIRES_ADMIN_REVIEW"];
const PROTECTED = ["mackay and daughters enterprises", "f e miller pools", "titan edge pty ltd"];
const STAFF_NAMES = ["mr k", "sarah lee lennets", "shannon saleh"];
const PILOT_QA_NAMES = ["test contractor 02", "pilot contractor", "pilot created contractor pty ltd", "pilot contractor pty ltd", "qa e2e contractor 20260605100015"];
const ID_FIELDS = ["contractorId", "contractorUid", "uid", "authUid", "userId", "ownerId", "linkedContractorId", "clientId", "organisationId", "organizationId", "id"];
const COLLECTIONS = ["users", "deals", "tenderPacks", "packRequests", "submissions", "contractorDocuments", "documents", "documentAnalyses", "documentAnalysis", "onboardingAcknowledgements", "acknowledgements", "complianceRecords", "auditLogs", "auditEvents", "governanceEvents", "invoices", "quotes", "hygieneRecords", "hygieneJobs", "hygieneCollections", "hygieneAssets"];
const INACTIVE = ["archived", "archive", "closed", "complete", "completed", "cancelled", "canceled", "deleted", "lost", "rejected", "declined"];
let adminModule: typeof import("../src/lib/firebase/admin") | null = null;
async function getAdminModule() { adminModule ??= await import("../src/lib/firebase/admin"); return adminModule; }
async function db() { return (await getAdminModule()).getFirebaseAdmin(); }
async function bucket() { return (await getAdminModule()).getFirebaseStorageBucket(); }
async function auth() { const { getAuth } = await import("firebase-admin/auth"); return getAuth(); }
const str = (v: unknown) => typeof v === "string" && v.trim() ? v.trim() : null;
const num = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : null;
const norm = (v: unknown) => str(v)?.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim() ?? "";
const iso = (v: unknown) => { if (typeof v === "number") return new Date(v).toISOString(); if (typeof v === "string" && v.trim()) { const d = new Date(v); return Number.isNaN(d.getTime()) ? null : d.toISOString(); } return null; };
const nameOf = (d: Raw) => str(d.companyName) ?? str(d.businessName) ?? str(d.legalName) ?? str(d.tradingName) ?? str(d.company) ?? str(d.name) ?? str(d.displayName) ?? str(d.contractorName);
const emailOf = (d: Raw) => (str(d.email) ?? str(d.contactEmail) ?? str(d.ownerEmail))?.toLowerCase() ?? null;
const phoneOf = (d: Raw) => str(d.phone) ?? str(d.phoneNumber) ?? str(d.contactPhone) ?? str(d.mobile);
const regOf = (d: Raw) => str(d.registrationNumber) ?? str(d.companyRegistrationNumber) ?? str(d.regNumber) ?? str(d.cipcNumber);
const taxOf = (d: Raw) => str(d.taxNumber) ?? str(d.taxPin) ?? str(d.taxReferenceNumber) ?? str(d.taxStatus) ?? str(d.taxPinStatus);
const csdOf = (d: Raw) => str(d.csdNumber) ?? str(d.csdMNumber) ?? str(d.mNumber);
const statusOf = (d: Raw) => str(d.onboardingStatus) ?? str(d.overallStatus) ?? str(d.status) ?? str(d.stage);
const scoreOf = (d: Raw) => num(d.readinessScore) ?? num(d.complianceScore) ?? num(d.complianceReadinessScore);
function ids(id: string, d: Raw) { const s = new Set<string>([id]); for (const f of ID_FIELDS) { const v = str(d[f]); if (v) s.add(v); } const e = emailOf(d); if (e) s.add(e); const n = nameOf(d); if (n) s.add(n); return s; }
function nids(id: string, d: Raw) { return new Set([...ids(id, d)].map(norm).filter(Boolean)); }
function matches(dep: Dep, exact: Set<string>, normalized: Set<string>) { for (const f of ID_FIELDS) { const v = dep.data[f]; if (typeof v === "string" && (exact.has(v) || normalized.has(norm(v)))) return true; if (Array.isArray(v) && v.some((x) => typeof x === "string" && (exact.has(x) || normalized.has(norm(x))))) return true; } const text = (dep.id + " " + JSON.stringify(dep.data)).toLowerCase(); return [...normalized].some((x) => x.length >= 8 && text.includes(x)); }
function active(dep: Dep) { if (!["deals", "tenderPacks", "packRequests", "submissions"].includes(dep.collection)) return false; const s = norm(dep.data.status ?? dep.data.stage ?? dep.data.tenderLockStatus ?? dep.data.workflowStatus); return !s || !INACTIVE.some((x) => s.includes(x)); }
const count = (deps: Dep[], names: string[]) => deps.filter((d) => names.includes(d.collection)).length;
const dupKey = (r: Row) => [r.registrationNumber, r.email, r.phone, r.csdNumber, r.taxNumberOrStatusIdentifier].map(norm).filter(Boolean).join("|") || norm(r.businessCompanyName);
const depScore = (r: Row) => Number(r.linkedUserCount ?? 0) + Number(r.linkedDealCount ?? 0) + Number(r.linkedTenderPackCount ?? 0) + Number(r.storageObjectCount ?? 0) + Number(r.linkedComplianceDocumentRecordCount ?? 0);
function classify(row: Row, deps: Dep[], retain: string | null, size: number): Row { const blocks = deps.filter(active).map((d) => d.collection + "/" + d.id); const n = norm(row.businessCompanyName); const text = [row.businessCompanyName, row.email].join(" ").toLowerCase(); const test = /\\b(test|qa|e2e|dummy|seed|pilot|demo|mock|sample|stability)\\b/.test(text); const staff = STAFF_NAMES.includes(n) || Boolean((row.firebaseAuthMatch as AuthHit | null)?.role && !["contractor", "client"].includes(norm((row.firebaseAuthMatch as AuthHit).role))); const meaningful = depScore(row) > 0; if (PROTECTED.includes(n)) return Object.assign(row, { recommendedClassification: "KEEP_ACTIVE", classificationConfidence: "HIGH", evidenceReason: "Explicitly protected business; must never be archived.", recommendedAction: "Keep active. Do not archive.", blockingDependencies: blocks, retainRecordId: row.firestoreDocumentId, archivingWouldPreserveCurrentReferencesSafely: false });
 if ((test || staff || (size > 1 && retain !== row.firestoreDocumentId)) && blocks.length) return Object.assign(row, { recommendedClassification: "BLOCKED_BY_DEPENDENCY", classificationConfidence: "HIGH", evidenceReason: "Archive-like signal exists but active production workflow dependencies are present.", recommendedAction: "Do not archive until blocking dependencies are reviewed.", blockingDependencies: blocks, retainRecordId: retain, archivingWouldPreserveCurrentReferencesSafely: false }); if (staff) return Object.assign(row, { recommendedClassification: "ARCHIVE_STAFF_PROFILE", classificationConfidence: "HIGH", evidenceReason: "Name/Auth/user role evidence indicates an internal staff profile stored as contractor.", recommendedAction: "Admin may archive after confirming no external contractor relationship.", blockingDependencies: blocks, retainRecordId: null, archivingWouldPreserveCurrentReferencesSafely: true });
 if (size > 1 && retain !== row.firestoreDocumentId) return Object.assign(row, { recommendedClassification: "ARCHIVE_DUPLICATE", classificationConfidence: "MEDIUM", evidenceReason: "Duplicate candidate by shared business identifiers or duplicate group; retain " + retain + ".", recommendedAction: "Admin may archive after confirming retained record.", blockingDependencies: blocks, retainRecordId: retain, archivingWouldPreserveCurrentReferencesSafely: true }); if (test && !meaningful) return Object.assign(row, { recommendedClassification: "ARCHIVE_TEST", classificationConfidence: "HIGH", evidenceReason: "Clear test/QA/pilot/stability signal and no meaningful production activity found.", recommendedAction: "Admin may archive after approval.", blockingDependencies: blocks, retainRecordId: null, archivingWouldPreserveCurrentReferencesSafely: true }); if (meaningful) return Object.assign(row, { recommendedClassification: "KEEP_ACTIVE", classificationConfidence: "MEDIUM", evidenceReason: "Meaningful user, deal, tender, document, compliance, audit, or storage dependency exists.", recommendedAction: "Keep active unless business owner approves otherwise.", blockingDependencies: blocks, retainRecordId: row.firestoreDocumentId, archivingWouldPreserveCurrentReferencesSafely: false });
 if (!row.workspaceId || row.readinessScore === null || Number(row.readinessScore) < 100) return Object.assign(row, { recommendedClassification: "KEEP_REVIEW", classificationConfidence: "MEDIUM", evidenceReason: "Likely genuine but incomplete, missing workspace data, or not fully ready.", recommendedAction: "Keep visible for admin review.", blockingDependencies: blocks, retainRecordId: row.firestoreDocumentId, archivingWouldPreserveCurrentReferencesSafely: false }); return Object.assign(row, { recommendedClassification: "UNKNOWN_REQUIRES_ADMIN_REVIEW", classificationConfidence: "LOW", evidenceReason: "Insufficient evidence for safe automated recommendation.", recommendedAction: "Require explicit admin decision.", blockingDependencies: blocks, retainRecordId: null, archivingWouldPreserveCurrentReferencesSafely: false }); }
async function readCollection(collection: string): Promise<Dep[]> { const snap = await (await db()).collection(collection).limit(5000).get().catch(() => null); return (snap?.docs ?? []).map((doc) => ({ collection, id: doc.id, data: (doc.data() ?? {}) as Raw })); }
async function readSubdocs(ids: string[]): Promise<Dep[]> { const out: Dep[] = []; for (const id of ids) { const snap = await (await db()).collection("contractors").doc(id).collection("documents").get().catch(() => null); for (const doc of snap?.docs ?? []) out.push({ collection: "contractors.documents", id: id + "/" + doc.id, data: (doc.data() ?? {}) as Raw }); } return out; }
async function readDeps() { return (await Promise.all(COLLECTIONS.map(readCollection))).flat(); }
async function authMatches(contractors: Array<{ id: string; data: Raw }>) { const out = new Map<string, AuthHit>(); const a = await auth(); let token: string | undefined; do { const page = await a.listUsers(1000, token); for (const u of page.users) for (const c of contractors) { const values = [u.uid, u.email ?? "", u.displayName ?? "", typeof u.customClaims?.contractorId === "string" ? u.customClaims.contractorId : ""]; const exact = ids(c.id, c.data); if (values.some((v) => v && (exact.has(v) || norm(v) === norm(c.id)))) out.set(c.id, { uid: u.uid, email: u.email ?? null, displayName: u.displayName ?? null, role: typeof u.customClaims?.role === "string" ? u.customClaims.role : null, contractorId: typeof u.customClaims?.contractorId === "string" ? u.customClaims.contractorId : null }); } token = page.pageToken; } while (token); return out; }
async function storageCounts(contractors: Array<{ id: string; data: Raw }>) { const out = new Map<string, number>(); for (const c of contractors) out.set(c.id, 0); const [files] = await (await bucket()).getFiles({ autoPaginate: true, maxResults: 10000 }).catch(() => [[]]); for (const f of files) { const fileName = f.name.toLowerCase(); for (const c of contractors) if ([...nids(c.id, c.data)].some((id) => id.length >= 8 && fileName.includes(id))) out.set(c.id, (out.get(c.id) ?? 0) + 1); } return out; }
function csv(v: unknown) { if (v === null || v === undefined) return ""; const s = typeof v === "string" ? v : JSON.stringify(v); return /[",\\n]/.test(s) ? "\\\"" + s.replace(/\\\"/g, "\\\"\\\"") + "\\\"" : s; }
function writeCsv(rows: Row[]) { const h = Object.keys(rows[0] ?? {}); fs.writeFileSync(CSV_REPORT, [h.join(","), ...rows.map((r) => h.map((k) => csv(r[k])).join(","))].join("\\n") + "\\n", "utf8"); }
function writeMd(report: Raw, rows: Row[], groups: Raw[]) { const counts = report.countsByClassification as Raw; const line = (r: Row) => "| " + [r.firestoreDocumentId, r.businessCompanyName, r.currentStatus, r.readinessScore, r.linkedUserCount, r.linkedDealCount, r.linkedTenderPackCount, r.linkedPackRequestCount, r.storageObjectCount, r.recommendedClassification, r.classificationConfidence, r.recommendedAction].map((x) => String(x ?? "").replace(/\\|/g, "/")).join(" | ") + " |"; const md = ["# Contractor Cleanup Report", "", "## Executive Summary", "- Generated at: " + report.generatedAt, "- Total contractors analysed: " + rows.length, "- Classification counts: " + Object.entries(counts).map(([k, v]) => k + "=" + v).join(", "), "- No production writes occurred.", "", "## Complete Contractor Classification Table", "| ID | Business | Status | Score | Users | Deals | Tenders | Pack Requests | Storage | Class | Confidence | Action |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |", ...rows.map(line),
"", "## Confirmed Active Contractors", ...rows.filter((r) => r.recommendedClassification === "KEEP_ACTIVE").map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.evidenceReason), "", "## Safe Archive Candidates", ...(report.safeArchiveCandidates as Row[]).map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.recommendedClassification), "", "## Dependency-Blocked Candidates", ...(report.dependencyBlockedCandidates as Row[]).map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.blockingDependencies.join(", ")), "", "## Staff-Profile Findings", ...(report.staffProfileFindings as Row[]).map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.recommendedClassification + ": " + r.evidenceReason),
"", "## Duplicate Groups", ...groups.map((g) => "- " + g.groupName + ": " + g.conclusion + "; retain=" + g.retainRecordId), "", "## Unknown / Manual-Review Records", ...rows.filter((r) => r.recommendedClassification === "KEEP_REVIEW" || r.recommendedClassification === "UNKNOWN_REQUIRES_ADMIN_REVIEW").map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.recommendedClassification), "", "## Recommended Archive Order", ...(report.recommendedArchiveOrder as Raw[]).map((r, i) => String(i + 1) + ". " + r.businessName + " (" + r.id + ") - " + r.classification), "", "## Records Requiring Explicit Admin Approval", ...rows.filter((r) => r.recommendedClassification !== "KEEP_ACTIVE").map((r) => "- " + r.businessCompanyName + " (" + r.firestoreDocumentId + ") - " + r.recommendedClassification), "", "## Production Write Confirmation", String(report.productionWriteConfirmation), ""].join("\\n"); fs.writeFileSync(MD_REPORT, md, "utf8"); }
async function main() { fs.mkdirSync(REPORT_DIR, { recursive: true }); const snap = await (await db()).collection("contractors").get(); const contractors = snap.docs.map((doc) => ({ id: doc.id, data: (doc.data() ?? {}) as Raw })); const [depsTop, authMap, storageMap, subdocs] = await Promise.all([readDeps(), authMatches(contractors), storageCounts(contractors), readSubdocs(contractors.map((c) => c.id))]); const depsAll = [...depsTop, ...subdocs]; const prelim = contractors.map((c) => { const exact = ids(c.id, c.data); const normalized = nids(c.id, c.data); const matched = depsAll.filter((d) => matches(d, exact, normalized)); const other: Record<string, number> = {}; for (const d of matched) if (!["users", "deals", "tenderPacks", "packRequests", "submissions", "onboardingAcknowledgements", "acknowledgements", "complianceRecords", "contractorDocuments", "documents", "documentAnalyses", "documentAnalysis", "contractors.documents", "auditLogs", "auditEvents", "governanceEvents"].includes(d.collection)) other[d.collection] = (other[d.collection] ?? 0) + 1;
 const row = { firestoreDocumentId: c.id, businessCompanyName: nameOf(c.data), email: emailOf(c.data), phone: phoneOf(c.data), registrationNumber: regOf(c.data), taxNumberOrStatusIdentifier: taxOf(c.data), csdNumber: csdOf(c.data), createdDate: iso(c.data.createdAt), lastUpdatedDate: iso(c.data.updatedAt), currentStatus: statusOf(c.data), readinessScore: scoreOf(c.data), workspaceId: str(c.data.workspaceId), contractorId: str(c.data.contractorId), uid: str(c.data.uid), authUid: str(c.data.authUid), userId: str(c.data.userId), archivedState: c.data.archived === true, firebaseAuthMatch: authMap.get(c.id) ?? null, storageObjectCount: storageMap.get(c.id) ?? 0, linkedUserCount: count(matched, ["users"]), linkedDealCount: count(matched, ["deals"]), linkedTenderPackCount: count(matched, ["tenderPacks"]), linkedPackRequestCount: count(matched, ["packRequests"]), linkedSubmissionCount: count(matched, ["submissions"]),
 linkedOnboardingAcknowledgementCount: count(matched, ["onboardingAcknowledgements", "acknowledgements"]), linkedComplianceDocumentRecordCount: count(matched, ["complianceRecords", "contractorDocuments", "documents", "documentAnalyses", "documentAnalysis", "contractors.documents"]), linkedAuditGovernanceEventCount: count(matched, ["auditLogs", "auditEvents", "governanceEvents"]), otherDiscoveredDependencyCount: Object.values(other).reduce((a, b) => a + b, 0), otherDiscoveredDependencies: other, activeProductionWorkflowDependsOnRecord: matched.some(active), archivingWouldPreserveCurrentReferencesSafely: false, recommendedClassification: "KEEP_REVIEW" as Category, classificationConfidence: "LOW" as Confidence, evidenceReason: "", recommendedAction: "", blockingDependencies: [], retainRecordId: null }; return { c, matched, row: row as Row }; });
 const groups = new Map<string, Row[]>(); for (const p of prelim) { const k = dupKey(p.row); if (!k) continue; const g = groups.get(k) ?? []; g.push(p.row); groups.set(k, g); } const retain = new Map<string, { id: string | null; size: number }>(); for (const g of groups.values()) if (g.length > 1) { const keep = [...g].sort((a, b) => depScore(b) - depScore(a) || Number(b.readinessScore ?? -1) - Number(a.readinessScore ?? -1))[0]?.firestoreDocumentId ?? null; for (const r of g) retain.set(r.firestoreDocumentId, { id: keep, size: g.length }); } const rows = prelim.map((p) => { const d = retain.get(p.row.firestoreDocumentId) ?? { id: null, size: 1 }; return classify(p.row, p.matched, d.id, d.size); }).sort((a, b) => String(a.businessCompanyName ?? "").localeCompare(String(b.businessCompanyName ?? "")));
 const duplicateGroups = [...groups.entries()].filter(([, g]) => g.length > 1).map(([key, g]) => ({ groupName: g[0].businessCompanyName ?? key, basis: g.some((r) => r.registrationNumber || r.email || r.phone || r.csdNumber || r.taxNumberOrStatusIdentifier) ? "shared identifier and/or matching business profile" : "name similarity only", conclusion: g.some((r) => r.registrationNumber || r.email || r.phone || r.csdNumber || r.taxNumberOrStatusIdentifier) ? "Potential true duplicate; retain strongest dependency/readiness record." : "Name-only duplicate group; requires admin review.", retainRecordId: retain.get(g[0].firestoreDocumentId)?.id ?? null, archiveCandidateIds: g.filter((r) => r.recommendedClassification.startsWith("ARCHIVE_")).map((r) => r.firestoreDocumentId), blockedRecordIds: g.filter((r) => r.recommendedClassification === "BLOCKED_BY_DEPENDENCY").map((r) => r.firestoreDocumentId), records: g })); const counts = Object.fromEntries(CATEGORIES.map((c) => [c, rows.filter((r) => r.recommendedClassification === c).length]));
 const report = { generatedAt: new Date().toISOString(), totalContractorsAnalysed: rows.length, countsByClassification: counts, rows, confirmedActiveContractors: rows.filter((r) => r.recommendedClassification === "KEEP_ACTIVE"), safeArchiveCandidates: rows.filter((r) => r.recommendedClassification.startsWith("ARCHIVE_") && !r.activeProductionWorkflowDependsOnRecord), dependencyBlockedCandidates: rows.filter((r) => r.recommendedClassification === "BLOCKED_BY_DEPENDENCY"), duplicateGroups, staffProfileFindings: rows.filter((r) => STAFF_NAMES.includes(norm(r.businessCompanyName))), pilotQaFindings: rows.filter((r) => PILOT_QA_NAMES.includes(norm(r.businessCompanyName))), stabilityCoFindings: rows.filter((r) => norm(r.businessCompanyName).includes("stability co")), unknownManualReviewRecords: rows.filter((r) => r.recommendedClassification === "KEEP_REVIEW" || r.recommendedClassification === "UNKNOWN_REQUIRES_ADMIN_REVIEW"), recommendedArchiveOrder: rows.filter((r) => r.recommendedClassification.startsWith("ARCHIVE_") && !r.activeProductionWorkflowDependsOnRecord).map((r) => ({ id: r.firestoreDocumentId, businessName: r.businessCompanyName, classification: r.recommendedClassification, action: r.recommendedAction })), productionWriteConfirmation: "No production writes occurred. This script only reads production services and writes local report files." };
 fs.writeFileSync(JSON_REPORT, JSON.stringify(report, null, 2), "utf8"); writeCsv(rows); writeMd(report, rows, duplicateGroups); console.log(JSON.stringify({ reportFiles: { json: JSON_REPORT, csv: CSV_REPORT, markdown: MD_REPORT }, summary: { totalContractorsAnalysed: rows.length, countsByClassification: counts, safeArchiveCandidates: report.safeArchiveCandidates.map((r) => r.firestoreDocumentId), dependencyBlockedCandidates: report.dependencyBlockedCandidates.map((r) => r.firestoreDocumentId), keepActive: report.confirmedActiveContractors.map((r) => r.firestoreDocumentId) } }, null, 2)); }
main().catch((error) => { console.error("[contractor-cleanup-report] failed", error instanceof Error ? error.stack ?? error.message : error); process.exitCode = 1; });

