export type ReportDocument = {
  name?: string;
  status?: string;
};

export type TenderReportInput = {
  clientName: string;
  documents: ReportDocument[];
  complianceScore: number;
  approvedBy: string;
  suggestions?: string[];
};

function cleanText(value: any): string {
  if (!value) return "";
  return String(value)
    .replace(/&/g, "")
    .replace(/[^a-zA-Z0-9\s:%.,-]/g, "")
    .trim();
}

export function generateTenderReport(data: TenderReportInput) {
  const date = new Date().toLocaleString();

  const documentLines = data.documents
    .map((doc) => {
      const normalizedStatus = cleanText(doc.status).toLowerCase();
      const status = normalizedStatus === "approved" ? "APPROVED" : "MISSING";
      return `- ${cleanText(doc.name || "Document")}: ${status}`;
    })
    .join("\n");

  const suggestionLines = (data.suggestions ?? [])
    .map((suggestion) => `- ${cleanText(suggestion)}`)
    .join("\n");

  return `
TORQUE EMPIRE
Tender Readiness Report
----------------------------------

Client: ${cleanText(data.clientName)}

Status: ${data.complianceScore === 100 ? "READY" : "NOT READY"}

Compliance Score: ${data.complianceScore}%

Documents:
${documentLines || "- None"}

AI Recommendations:
${suggestionLines || "- None"}

Approved by: ${cleanText(data.approvedBy)}
Date: ${date}

----------------------------------
Generated by Torque Empire System
`;
}
