export const QS_STANDARD_UNITS = [
  { label: "Each", symbol: "each", aliases: ["ea", "unit"] },
  { label: "Box", symbol: "box", aliases: ["bx"] },
  { label: "Pack", symbol: "pack", aliases: ["pkt"] },
  { label: "Bag", symbol: "bag", aliases: [] },
  { label: "kg", symbol: "kg", aliases: ["kilogram", "kilograms"] },
  { label: "Ton", symbol: "ton", aliases: ["t", "tonne"] },
  { label: "Litre", symbol: "litre", aliases: ["l", "liter"] },
  { label: "m", symbol: "m", aliases: ["metre", "meter"] },
  { label: "m2", symbol: "m2", aliases: ["m²", "square metre", "square meter"] },
  { label: "m3", symbol: "m3", aliases: ["m³", "cubic metre", "cubic meter"] },
  { label: "Roll", symbol: "roll", aliases: [] },
  { label: "Bundle", symbol: "bundle", aliases: [] },
  { label: "Pair", symbol: "pair", aliases: [] },
  { label: "Sheet", symbol: "sheet", aliases: [] },
] as const;

export const QS_MATERIAL_CATEGORY_SEEDS = [
  "Concrete",
  "Aggregates",
  "Sand",
  "Bricks",
  "Blocks",
  "Steel",
  "Roofing",
  "Timber",
  "Doors",
  "Windows",
  "Paint",
  "Tiles",
  "Electrical",
  "Lighting",
  "Plumbing",
  "Sanitary",
  "Security",
  "Hardware",
  "Fasteners",
  "Ceilings",
  "Drywall",
  "Flooring",
  "Civil Works",
  "Road Construction",
  "Landscaping",
  "PPE",
  "Tools",
  "Plant Hire",
] as const;
